issuer: "{{ .Env.ISSUER_URL }}"

web:
  http: 0.0.0.0:7011
  allowedOrigins: ["{{ .Env.APP_URL }}"]

storage:
  type: postgres
  config:
    user: dex
    password: "{{ .Env.POSTGRES_PASSWORD }}"
    host: postgres
    port: {{ .Env.POSTGRES_PORT }}
    database: dex
    ssl:
      mode: disable

oauth2:
  responseTypes: ["code"]
  skipApprovalScreen: true
  alwaysShowLoginScreen: true
  # passwordConnector: local
  grantTypes:
    - "authorization_code"
    - "refresh_token"
    - "urn:ietf:params:oauth:grant-type:token-exchange"

staticClients:
  - id: "{{ .Env.OIDC_CLIENT_ID }}"
    name: "Rezible"
    public: true
    redirectURIs: ["{{ .Env.OIDC_CLIENT_REDIRECT_URI }}"]

connectors:
  - type: google
    id: google
    name: Google (OIDC)
    config:
      clientID: $GOOGLE_OIDC_CLIENT_ID
      clientSecret: $GOOGLE_OIDC_CLIENT_SECRET
      redirectURI: $GOOGLE_OIDC_CLIENT_REDIRECT_URI
      promptType: ""

enablePasswordDB: true
staticPasswords:
  # password: $(echo "foobar1" | htpasswd -BinC 10 admin | cut -d: -f2)
  - email: "admin@dev.rezible.com"
    username: "admin"
    userID: "cd8cc83f-de81-4f05-a64d-5e4105a35142"
    hash: "$2y$10$NI22AXHCKIordm2Y3pf0RuNVEUHvktOYruQ6/hli8UcvTEBhpX2KG"
  - email: "user@dev.rezible.com"
    username: "user"
    userID: "00cb6dd1-6be0-4b2a-83ad-4f16468f9055"
    hash: "$2y$10$NI22AXHCKIordm2Y3pf0RuNVEUHvktOYruQ6/hli8UcvTEBhpX2KG"
