CREATE USER dex WITH LOGIN PASSWORD '{{ .DexPassword }}';
CREATE DATABASE dex OWNER dex;
REVOKE ALL ON DATABASE dex FROM PUBLIC;
GRANT CONNECT ON DATABASE dex TO dex;

CREATE USER rez_admin WITH LOGIN CREATEDB PASSWORD '{{ .RezAdminPassword }}';
CREATE USER rez_app WITH LOGIN PASSWORD '{{ .RezAppPassword }}';
CREATE USER rez_documents WITH LOGIN PASSWORD '{{ .RezDocumentsPassword }}';

CREATE DATABASE rezible OWNER rez_admin;
REVOKE ALL ON DATABASE rezible FROM PUBLIC;

GRANT CONNECT ON DATABASE rezible TO rez_app;
GRANT CONNECT ON DATABASE rezible TO rez_documents;

\connect rezible

CREATE SCHEMA IF NOT EXISTS river AUTHORIZATION rez_admin;
CREATE SCHEMA IF NOT EXISTS rezible AUTHORIZATION rez_admin;

GRANT USAGE ON SCHEMA rezible TO rez_app;
GRANT USAGE ON SCHEMA rezible TO rez_documents;
GRANT USAGE ON SCHEMA river TO rez_app;

ALTER DEFAULT PRIVILEGES FOR ROLE rez_admin IN SCHEMA rezible
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rez_app;
ALTER DEFAULT PRIVILEGES FOR ROLE rez_admin IN SCHEMA rezible
    GRANT USAGE, SELECT ON SEQUENCES TO rez_app;

ALTER DEFAULT PRIVILEGES FOR ROLE rez_admin IN SCHEMA river
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rez_app;
ALTER DEFAULT PRIVILEGES FOR ROLE rez_admin IN SCHEMA river
    GRANT USAGE, SELECT ON SEQUENCES TO rez_app;

ALTER ROLE rez_admin SET search_path TO rezible;
ALTER ROLE rez_app SET search_path TO rezible, river;
ALTER ROLE rez_documents SET search_path TO rezible;