Port: 8080
ExternalPort: 443
ExternalSecure: true
TLS:
  Enabled: false

Database:
  postgres:
    Host: postgres
    Port: 5432
    Database: zitadel
    User:
      Username: zitadel

Instrumentation:
  Log:
    Format: "text"

DefaultInstance:
  WebKeys:
    Type: "ecdsa"
    Config:
      EllipticCurve: "P256" # ZITADEL_DEFAULTINSTANCE_WEBKEYS_CONFIG_CURVE
  Features:
    LoginDefaultOrg: false
    LoginV2:
      # broken with generic oidc https://github.com/zitadel/zitadel/issues/11421
      Required: false
  LabelPolicy:
    HideLoginNameSuffix: true
    ErrorMsgPopup: true
    DisableWatermark: true

ServicePing:
  Enabled: false
