// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/rezible/rezible/ent/agentrun"
	"github.com/rezible/rezible/ent/agentrunsubject"
	"github.com/rezible/rezible/ent/internal"
	"github.com/rezible/rezible/ent/predicate"
	"github.com/rezible/rezible/ent/tenant"
)

// AgentRunSubjectQuery is the builder for querying AgentRunSubject entities.
type AgentRunSubjectQuery struct {
	config
	ctx          *QueryContext
	order        []agentrunsubject.OrderOption
	inters       []Interceptor
	predicates   []predicate.AgentRunSubject
	withTenant   *TenantQuery
	withAgentRun *AgentRunQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AgentRunSubjectQuery builder.
func (_q *AgentRunSubjectQuery) Where(ps ...predicate.AgentRunSubject) *AgentRunSubjectQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AgentRunSubjectQuery) Limit(limit int) *AgentRunSubjectQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AgentRunSubjectQuery) Offset(offset int) *AgentRunSubjectQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AgentRunSubjectQuery) Unique(unique bool) *AgentRunSubjectQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AgentRunSubjectQuery) Order(o ...agentrunsubject.OrderOption) *AgentRunSubjectQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTenant chains the current query on the "tenant" edge.
func (_q *AgentRunSubjectQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agentrunsubject.Table, agentrunsubject.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, agentrunsubject.TenantTable, agentrunsubject.TenantColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.Tenant
		step.Edge.Schema = schemaConfig.AgentRunSubject
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAgentRun chains the current query on the "agent_run" edge.
func (_q *AgentRunSubjectQuery) QueryAgentRun() *AgentRunQuery {
	query := (&AgentRunClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agentrunsubject.Table, agentrunsubject.FieldID, selector),
			sqlgraph.To(agentrun.Table, agentrun.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, agentrunsubject.AgentRunTable, agentrunsubject.AgentRunColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.AgentRun
		step.Edge.Schema = schemaConfig.AgentRunSubject
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AgentRunSubject entity from the query.
// Returns a *NotFoundError when no AgentRunSubject was found.
func (_q *AgentRunSubjectQuery) First(ctx context.Context) (*AgentRunSubject, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{agentrunsubject.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AgentRunSubjectQuery) FirstX(ctx context.Context) *AgentRunSubject {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AgentRunSubject ID from the query.
// Returns a *NotFoundError when no AgentRunSubject ID was found.
func (_q *AgentRunSubjectQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{agentrunsubject.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AgentRunSubjectQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AgentRunSubject entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AgentRunSubject entity is found.
// Returns a *NotFoundError when no AgentRunSubject entities are found.
func (_q *AgentRunSubjectQuery) Only(ctx context.Context) (*AgentRunSubject, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{agentrunsubject.Label}
	default:
		return nil, &NotSingularError{agentrunsubject.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AgentRunSubjectQuery) OnlyX(ctx context.Context) *AgentRunSubject {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AgentRunSubject ID in the query.
// Returns a *NotSingularError when more than one AgentRunSubject ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AgentRunSubjectQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{agentrunsubject.Label}
	default:
		err = &NotSingularError{agentrunsubject.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AgentRunSubjectQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AgentRunSubjects.
func (_q *AgentRunSubjectQuery) All(ctx context.Context) ([]*AgentRunSubject, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AgentRunSubject, *AgentRunSubjectQuery]()
	return withInterceptors[[]*AgentRunSubject](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AgentRunSubjectQuery) AllX(ctx context.Context) []*AgentRunSubject {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AgentRunSubject IDs.
func (_q *AgentRunSubjectQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(agentrunsubject.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AgentRunSubjectQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AgentRunSubjectQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AgentRunSubjectQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AgentRunSubjectQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AgentRunSubjectQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AgentRunSubjectQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AgentRunSubjectQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AgentRunSubjectQuery) Clone() *AgentRunSubjectQuery {
	if _q == nil {
		return nil
	}
	return &AgentRunSubjectQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]agentrunsubject.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.AgentRunSubject{}, _q.predicates...),
		withTenant:   _q.withTenant.Clone(),
		withAgentRun: _q.withAgentRun.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AgentRunSubjectQuery) WithTenant(opts ...func(*TenantQuery)) *AgentRunSubjectQuery {
	query := (&TenantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTenant = query
	return _q
}

// WithAgentRun tells the query-builder to eager-load the nodes that are connected to
// the "agent_run" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AgentRunSubjectQuery) WithAgentRun(opts ...func(*AgentRunQuery)) *AgentRunSubjectQuery {
	query := (&AgentRunClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAgentRun = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID int `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AgentRunSubject.Query().
//		GroupBy(agentrunsubject.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AgentRunSubjectQuery) GroupBy(field string, fields ...string) *AgentRunSubjectGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AgentRunSubjectGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = agentrunsubject.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID int `json:"tenant_id,omitempty"`
//	}
//
//	client.AgentRunSubject.Query().
//		Select(agentrunsubject.FieldTenantID).
//		Scan(ctx, &v)
func (_q *AgentRunSubjectQuery) Select(fields ...string) *AgentRunSubjectSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AgentRunSubjectSelect{AgentRunSubjectQuery: _q}
	sbuild.label = agentrunsubject.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AgentRunSubjectSelect configured with the given aggregations.
func (_q *AgentRunSubjectQuery) Aggregate(fns ...AggregateFunc) *AgentRunSubjectSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AgentRunSubjectQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !agentrunsubject.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if agentrunsubject.Policy == nil {
		return errors.New("ent: uninitialized agentrunsubject.Policy (forgotten import ent/runtime?)")
	}
	if err := agentrunsubject.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *AgentRunSubjectQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AgentRunSubject, error) {
	var (
		nodes       = []*AgentRunSubject{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withTenant != nil,
			_q.withAgentRun != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AgentRunSubject).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AgentRunSubject{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.AgentRunSubject
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTenant; query != nil {
		if err := _q.loadTenant(ctx, query, nodes, nil,
			func(n *AgentRunSubject, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAgentRun; query != nil {
		if err := _q.loadAgentRun(ctx, query, nodes, nil,
			func(n *AgentRunSubject, e *AgentRun) { n.Edges.AgentRun = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AgentRunSubjectQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*AgentRunSubject, init func(*AgentRunSubject), assign func(*AgentRunSubject, *Tenant)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AgentRunSubject)
	for i := range nodes {
		fk := nodes[i].TenantID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AgentRunSubjectQuery) loadAgentRun(ctx context.Context, query *AgentRunQuery, nodes []*AgentRunSubject, init func(*AgentRunSubject), assign func(*AgentRunSubject, *AgentRun)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AgentRunSubject)
	for i := range nodes {
		fk := nodes[i].AgentRunID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(agentrun.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "agent_run_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *AgentRunSubjectQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.AgentRunSubject
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AgentRunSubjectQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(agentrunsubject.Table, agentrunsubject.Columns, sqlgraph.NewFieldSpec(agentrunsubject.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentrunsubject.FieldID)
		for i := range fields {
			if fields[i] != agentrunsubject.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTenant != nil {
			_spec.Node.AddColumnOnce(agentrunsubject.FieldTenantID)
		}
		if _q.withAgentRun != nil {
			_spec.Node.AddColumnOnce(agentrunsubject.FieldAgentRunID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AgentRunSubjectQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(agentrunsubject.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = agentrunsubject.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.AgentRunSubject)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *AgentRunSubjectQuery) Modify(modifiers ...func(s *sql.Selector)) *AgentRunSubjectSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// AgentRunSubjectGroupBy is the group-by builder for AgentRunSubject entities.
type AgentRunSubjectGroupBy struct {
	selector
	build *AgentRunSubjectQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AgentRunSubjectGroupBy) Aggregate(fns ...AggregateFunc) *AgentRunSubjectGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AgentRunSubjectGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentRunSubjectQuery, *AgentRunSubjectGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AgentRunSubjectGroupBy) sqlScan(ctx context.Context, root *AgentRunSubjectQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AgentRunSubjectSelect is the builder for selecting fields of AgentRunSubject entities.
type AgentRunSubjectSelect struct {
	*AgentRunSubjectQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AgentRunSubjectSelect) Aggregate(fns ...AggregateFunc) *AgentRunSubjectSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AgentRunSubjectSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentRunSubjectQuery, *AgentRunSubjectSelect](ctx, _s.AgentRunSubjectQuery, _s, _s.inters, v)
}

func (_s *AgentRunSubjectSelect) sqlScan(ctx context.Context, root *AgentRunSubjectQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *AgentRunSubjectSelect) Modify(modifiers ...func(s *sql.Selector)) *AgentRunSubjectSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
