// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/firebase/genkit/go/ai"
	"github.com/google/uuid"
	"github.com/rezible/rezible/ent/agentartifact"
	"github.com/rezible/rezible/ent/agentturn"
	"github.com/rezible/rezible/ent/internal"
	"github.com/rezible/rezible/ent/predicate"
)

// AgentArtifactUpdate is the builder for updating AgentArtifact entities.
type AgentArtifactUpdate struct {
	config
	hooks     []Hook
	mutation  *AgentArtifactMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AgentArtifactUpdate builder.
func (_u *AgentArtifactUpdate) Where(ps ...predicate.AgentArtifact) *AgentArtifactUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AgentArtifactUpdate) SetCreatedAt(v time.Time) *AgentArtifactUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AgentArtifactUpdate) SetNillableCreatedAt(v *time.Time) *AgentArtifactUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentArtifactUpdate) SetUpdatedAt(v time.Time) *AgentArtifactUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastAgentTurnID sets the "last_agent_turn_id" field.
func (_u *AgentArtifactUpdate) SetLastAgentTurnID(v uuid.UUID) *AgentArtifactUpdate {
	_u.mutation.SetLastAgentTurnID(v)
	return _u
}

// SetNillableLastAgentTurnID sets the "last_agent_turn_id" field if the given value is not nil.
func (_u *AgentArtifactUpdate) SetNillableLastAgentTurnID(v *uuid.UUID) *AgentArtifactUpdate {
	if v != nil {
		_u.SetLastAgentTurnID(*v)
	}
	return _u
}

// ClearLastAgentTurnID clears the value of the "last_agent_turn_id" field.
func (_u *AgentArtifactUpdate) ClearLastAgentTurnID() *AgentArtifactUpdate {
	_u.mutation.ClearLastAgentTurnID()
	return _u
}

// SetName sets the "name" field.
func (_u *AgentArtifactUpdate) SetName(v string) *AgentArtifactUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentArtifactUpdate) SetNillableName(v *string) *AgentArtifactUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetParts sets the "parts" field.
func (_u *AgentArtifactUpdate) SetParts(v []*ai.Part) *AgentArtifactUpdate {
	_u.mutation.SetParts(v)
	return _u
}

// AppendParts appends value to the "parts" field.
func (_u *AgentArtifactUpdate) AppendParts(v []*ai.Part) *AgentArtifactUpdate {
	_u.mutation.AppendParts(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AgentArtifactUpdate) SetMetadata(v map[string]interface{}) *AgentArtifactUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetAgentTurnID sets the "agent_turn" edge to the AgentTurn entity by ID.
func (_u *AgentArtifactUpdate) SetAgentTurnID(id uuid.UUID) *AgentArtifactUpdate {
	_u.mutation.SetAgentTurnID(id)
	return _u
}

// SetNillableAgentTurnID sets the "agent_turn" edge to the AgentTurn entity by ID if the given value is not nil.
func (_u *AgentArtifactUpdate) SetNillableAgentTurnID(id *uuid.UUID) *AgentArtifactUpdate {
	if id != nil {
		_u = _u.SetAgentTurnID(*id)
	}
	return _u
}

// SetAgentTurn sets the "agent_turn" edge to the AgentTurn entity.
func (_u *AgentArtifactUpdate) SetAgentTurn(v *AgentTurn) *AgentArtifactUpdate {
	return _u.SetAgentTurnID(v.ID)
}

// Mutation returns the AgentArtifactMutation object of the builder.
func (_u *AgentArtifactUpdate) Mutation() *AgentArtifactMutation {
	return _u.mutation
}

// ClearAgentTurn clears the "agent_turn" edge to the AgentTurn entity.
func (_u *AgentArtifactUpdate) ClearAgentTurn() *AgentArtifactUpdate {
	_u.mutation.ClearAgentTurn()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentArtifactUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentArtifactUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentArtifactUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentArtifactUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentArtifactUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if agentartifact.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentartifact.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := agentartifact.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentArtifactUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := agentartifact.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentArtifact.name": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentArtifact.tenant"`)
	}
	if _u.mutation.AgentSessionCleared() && len(_u.mutation.AgentSessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentArtifact.agent_session"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AgentArtifactUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AgentArtifactUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AgentArtifactUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentartifact.Table, agentartifact.Columns, sqlgraph.NewFieldSpec(agentartifact.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(agentartifact.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentartifact.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agentartifact.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parts(); ok {
		_spec.SetField(agentartifact.FieldParts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedParts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentartifact.FieldParts, value)
		})
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(agentartifact.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.AgentTurnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentartifact.AgentTurnTable,
			Columns: []string{agentartifact.AgentTurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentturn.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.AgentArtifact
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentTurnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentartifact.AgentTurnTable,
			Columns: []string{agentartifact.AgentTurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentturn.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.AgentArtifact
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.AgentArtifact
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentArtifactUpdateOne is the builder for updating a single AgentArtifact entity.
type AgentArtifactUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AgentArtifactMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedAt sets the "created_at" field.
func (_u *AgentArtifactUpdateOne) SetCreatedAt(v time.Time) *AgentArtifactUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AgentArtifactUpdateOne) SetNillableCreatedAt(v *time.Time) *AgentArtifactUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentArtifactUpdateOne) SetUpdatedAt(v time.Time) *AgentArtifactUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastAgentTurnID sets the "last_agent_turn_id" field.
func (_u *AgentArtifactUpdateOne) SetLastAgentTurnID(v uuid.UUID) *AgentArtifactUpdateOne {
	_u.mutation.SetLastAgentTurnID(v)
	return _u
}

// SetNillableLastAgentTurnID sets the "last_agent_turn_id" field if the given value is not nil.
func (_u *AgentArtifactUpdateOne) SetNillableLastAgentTurnID(v *uuid.UUID) *AgentArtifactUpdateOne {
	if v != nil {
		_u.SetLastAgentTurnID(*v)
	}
	return _u
}

// ClearLastAgentTurnID clears the value of the "last_agent_turn_id" field.
func (_u *AgentArtifactUpdateOne) ClearLastAgentTurnID() *AgentArtifactUpdateOne {
	_u.mutation.ClearLastAgentTurnID()
	return _u
}

// SetName sets the "name" field.
func (_u *AgentArtifactUpdateOne) SetName(v string) *AgentArtifactUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentArtifactUpdateOne) SetNillableName(v *string) *AgentArtifactUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetParts sets the "parts" field.
func (_u *AgentArtifactUpdateOne) SetParts(v []*ai.Part) *AgentArtifactUpdateOne {
	_u.mutation.SetParts(v)
	return _u
}

// AppendParts appends value to the "parts" field.
func (_u *AgentArtifactUpdateOne) AppendParts(v []*ai.Part) *AgentArtifactUpdateOne {
	_u.mutation.AppendParts(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AgentArtifactUpdateOne) SetMetadata(v map[string]interface{}) *AgentArtifactUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetAgentTurnID sets the "agent_turn" edge to the AgentTurn entity by ID.
func (_u *AgentArtifactUpdateOne) SetAgentTurnID(id uuid.UUID) *AgentArtifactUpdateOne {
	_u.mutation.SetAgentTurnID(id)
	return _u
}

// SetNillableAgentTurnID sets the "agent_turn" edge to the AgentTurn entity by ID if the given value is not nil.
func (_u *AgentArtifactUpdateOne) SetNillableAgentTurnID(id *uuid.UUID) *AgentArtifactUpdateOne {
	if id != nil {
		_u = _u.SetAgentTurnID(*id)
	}
	return _u
}

// SetAgentTurn sets the "agent_turn" edge to the AgentTurn entity.
func (_u *AgentArtifactUpdateOne) SetAgentTurn(v *AgentTurn) *AgentArtifactUpdateOne {
	return _u.SetAgentTurnID(v.ID)
}

// Mutation returns the AgentArtifactMutation object of the builder.
func (_u *AgentArtifactUpdateOne) Mutation() *AgentArtifactMutation {
	return _u.mutation
}

// ClearAgentTurn clears the "agent_turn" edge to the AgentTurn entity.
func (_u *AgentArtifactUpdateOne) ClearAgentTurn() *AgentArtifactUpdateOne {
	_u.mutation.ClearAgentTurn()
	return _u
}

// Where appends a list predicates to the AgentArtifactUpdate builder.
func (_u *AgentArtifactUpdateOne) Where(ps ...predicate.AgentArtifact) *AgentArtifactUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentArtifactUpdateOne) Select(field string, fields ...string) *AgentArtifactUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentArtifact entity.
func (_u *AgentArtifactUpdateOne) Save(ctx context.Context) (*AgentArtifact, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentArtifactUpdateOne) SaveX(ctx context.Context) *AgentArtifact {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentArtifactUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentArtifactUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentArtifactUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if agentartifact.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentartifact.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := agentartifact.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentArtifactUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := agentartifact.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentArtifact.name": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentArtifact.tenant"`)
	}
	if _u.mutation.AgentSessionCleared() && len(_u.mutation.AgentSessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentArtifact.agent_session"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AgentArtifactUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AgentArtifactUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AgentArtifactUpdateOne) sqlSave(ctx context.Context) (_node *AgentArtifact, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentartifact.Table, agentartifact.Columns, sqlgraph.NewFieldSpec(agentartifact.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentArtifact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentartifact.FieldID)
		for _, f := range fields {
			if !agentartifact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentartifact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(agentartifact.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentartifact.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agentartifact.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parts(); ok {
		_spec.SetField(agentartifact.FieldParts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedParts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentartifact.FieldParts, value)
		})
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(agentartifact.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.AgentTurnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentartifact.AgentTurnTable,
			Columns: []string{agentartifact.AgentTurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentturn.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.AgentArtifact
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentTurnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentartifact.AgentTurnTable,
			Columns: []string{agentartifact.AgentTurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentturn.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.AgentArtifact
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.AgentArtifact
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	_node = &AgentArtifact{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
