// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/rezible/rezible/ent/incidenttimelineevent"
	"github.com/rezible/rezible/ent/incidenttimelineeventcontributingfactor"
	"github.com/rezible/rezible/ent/tenant"
)

// IncidentTimelineEventContributingFactor is the model entity for the IncidentTimelineEventContributingFactor schema.
type IncidentTimelineEventContributingFactor struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int `json:"tenant_id,omitempty"`
	// FactorType holds the value of the "factor_type" field.
	FactorType string `json:"factor_type,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IncidentTimelineEventContributingFactorQuery when eager-loading is set.
	Edges                           IncidentTimelineEventContributingFactorEdges `json:"edges"`
	incident_timeline_event_factors *uuid.UUID
	selectValues                    sql.SelectValues
}

// IncidentTimelineEventContributingFactorEdges holds the relations/edges for other nodes in the graph.
type IncidentTimelineEventContributingFactorEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Event holds the value of the event edge.
	Event *IncidentTimelineEvent `json:"event,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IncidentTimelineEventContributingFactorEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// EventOrErr returns the Event value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IncidentTimelineEventContributingFactorEdges) EventOrErr() (*IncidentTimelineEvent, error) {
	if e.Event != nil {
		return e.Event, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: incidenttimelineevent.Label}
	}
	return nil, &NotLoadedError{edge: "event"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IncidentTimelineEventContributingFactor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case incidenttimelineeventcontributingfactor.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case incidenttimelineeventcontributingfactor.FieldFactorType, incidenttimelineeventcontributingfactor.FieldDescription:
			values[i] = new(sql.NullString)
		case incidenttimelineeventcontributingfactor.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case incidenttimelineeventcontributingfactor.FieldID:
			values[i] = new(uuid.UUID)
		case incidenttimelineeventcontributingfactor.ForeignKeys[0]: // incident_timeline_event_factors
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IncidentTimelineEventContributingFactor fields.
func (_m *IncidentTimelineEventContributingFactor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case incidenttimelineeventcontributingfactor.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case incidenttimelineeventcontributingfactor.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = int(value.Int64)
			}
		case incidenttimelineeventcontributingfactor.FieldFactorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field factor_type", values[i])
			} else if value.Valid {
				_m.FactorType = value.String
			}
		case incidenttimelineeventcontributingfactor.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case incidenttimelineeventcontributingfactor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case incidenttimelineeventcontributingfactor.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field incident_timeline_event_factors", values[i])
			} else if value.Valid {
				_m.incident_timeline_event_factors = new(uuid.UUID)
				*_m.incident_timeline_event_factors = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IncidentTimelineEventContributingFactor.
// This includes values selected through modifiers, order, etc.
func (_m *IncidentTimelineEventContributingFactor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the IncidentTimelineEventContributingFactor entity.
func (_m *IncidentTimelineEventContributingFactor) QueryTenant() *TenantQuery {
	return NewIncidentTimelineEventContributingFactorClient(_m.config).QueryTenant(_m)
}

// QueryEvent queries the "event" edge of the IncidentTimelineEventContributingFactor entity.
func (_m *IncidentTimelineEventContributingFactor) QueryEvent() *IncidentTimelineEventQuery {
	return NewIncidentTimelineEventContributingFactorClient(_m.config).QueryEvent(_m)
}

// Update returns a builder for updating this IncidentTimelineEventContributingFactor.
// Note that you need to call IncidentTimelineEventContributingFactor.Unwrap() before calling this method if this IncidentTimelineEventContributingFactor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IncidentTimelineEventContributingFactor) Update() *IncidentTimelineEventContributingFactorUpdateOne {
	return NewIncidentTimelineEventContributingFactorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IncidentTimelineEventContributingFactor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IncidentTimelineEventContributingFactor) Unwrap() *IncidentTimelineEventContributingFactor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IncidentTimelineEventContributingFactor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IncidentTimelineEventContributingFactor) String() string {
	var builder strings.Builder
	builder.WriteString("IncidentTimelineEventContributingFactor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("factor_type=")
	builder.WriteString(_m.FactorType)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// IncidentTimelineEventContributingFactors is a parsable slice of IncidentTimelineEventContributingFactor.
type IncidentTimelineEventContributingFactors []*IncidentTimelineEventContributingFactor
