// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rezible/rezible/ent/integrationeventsynccursor"
	"github.com/rezible/rezible/ent/internal"
	"github.com/rezible/rezible/ent/predicate"
)

// IntegrationEventSyncCursorDelete is the builder for deleting a IntegrationEventSyncCursor entity.
type IntegrationEventSyncCursorDelete struct {
	config
	hooks    []Hook
	mutation *IntegrationEventSyncCursorMutation
}

// Where appends a list predicates to the IntegrationEventSyncCursorDelete builder.
func (_d *IntegrationEventSyncCursorDelete) Where(ps ...predicate.IntegrationEventSyncCursor) *IntegrationEventSyncCursorDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *IntegrationEventSyncCursorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IntegrationEventSyncCursorDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *IntegrationEventSyncCursorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(integrationeventsynccursor.Table, sqlgraph.NewFieldSpec(integrationeventsynccursor.FieldID, field.TypeUUID))
	_spec.Node.Schema = _d.schemaConfig.IntegrationEventSyncCursor
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// IntegrationEventSyncCursorDeleteOne is the builder for deleting a single IntegrationEventSyncCursor entity.
type IntegrationEventSyncCursorDeleteOne struct {
	_d *IntegrationEventSyncCursorDelete
}

// Where appends a list predicates to the IntegrationEventSyncCursorDelete builder.
func (_d *IntegrationEventSyncCursorDeleteOne) Where(ps ...predicate.IntegrationEventSyncCursor) *IntegrationEventSyncCursorDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *IntegrationEventSyncCursorDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{integrationeventsynccursor.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IntegrationEventSyncCursorDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
