// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/rezible/rezible/ent/internal"
	"github.com/rezible/rezible/ent/knowledgeentityalias"
	"github.com/rezible/rezible/ent/knowledgefacthistory"
	"github.com/rezible/rezible/ent/knowledgerelationship"
	"github.com/rezible/rezible/ent/normalizedevent"
	"github.com/rezible/rezible/ent/predicate"
)

// KnowledgeFactHistoryUpdate is the builder for updating KnowledgeFactHistory entities.
type KnowledgeFactHistoryUpdate struct {
	config
	hooks     []Hook
	mutation  *KnowledgeFactHistoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the KnowledgeFactHistoryUpdate builder.
func (_u *KnowledgeFactHistoryUpdate) Where(ps ...predicate.KnowledgeFactHistory) *KnowledgeFactHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFactKind sets the "fact_kind" field.
func (_u *KnowledgeFactHistoryUpdate) SetFactKind(v knowledgefacthistory.FactKind) *KnowledgeFactHistoryUpdate {
	_u.mutation.SetFactKind(v)
	return _u
}

// SetNillableFactKind sets the "fact_kind" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdate) SetNillableFactKind(v *knowledgefacthistory.FactKind) *KnowledgeFactHistoryUpdate {
	if v != nil {
		_u.SetFactKind(*v)
	}
	return _u
}

// ClearFactKind clears the value of the "fact_kind" field.
func (_u *KnowledgeFactHistoryUpdate) ClearFactKind() *KnowledgeFactHistoryUpdate {
	_u.mutation.ClearFactKind()
	return _u
}

// SetAliasID sets the "alias_id" field.
func (_u *KnowledgeFactHistoryUpdate) SetAliasID(v uuid.UUID) *KnowledgeFactHistoryUpdate {
	_u.mutation.SetAliasID(v)
	return _u
}

// SetNillableAliasID sets the "alias_id" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdate) SetNillableAliasID(v *uuid.UUID) *KnowledgeFactHistoryUpdate {
	if v != nil {
		_u.SetAliasID(*v)
	}
	return _u
}

// ClearAliasID clears the value of the "alias_id" field.
func (_u *KnowledgeFactHistoryUpdate) ClearAliasID() *KnowledgeFactHistoryUpdate {
	_u.mutation.ClearAliasID()
	return _u
}

// SetRelationshipID sets the "relationship_id" field.
func (_u *KnowledgeFactHistoryUpdate) SetRelationshipID(v uuid.UUID) *KnowledgeFactHistoryUpdate {
	_u.mutation.SetRelationshipID(v)
	return _u
}

// SetNillableRelationshipID sets the "relationship_id" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdate) SetNillableRelationshipID(v *uuid.UUID) *KnowledgeFactHistoryUpdate {
	if v != nil {
		_u.SetRelationshipID(*v)
	}
	return _u
}

// ClearRelationshipID clears the value of the "relationship_id" field.
func (_u *KnowledgeFactHistoryUpdate) ClearRelationshipID() *KnowledgeFactHistoryUpdate {
	_u.mutation.ClearRelationshipID()
	return _u
}

// SetNormalizedEventID sets the "normalized_event_id" field.
func (_u *KnowledgeFactHistoryUpdate) SetNormalizedEventID(v uuid.UUID) *KnowledgeFactHistoryUpdate {
	_u.mutation.SetNormalizedEventID(v)
	return _u
}

// SetNillableNormalizedEventID sets the "normalized_event_id" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdate) SetNillableNormalizedEventID(v *uuid.UUID) *KnowledgeFactHistoryUpdate {
	if v != nil {
		_u.SetNormalizedEventID(*v)
	}
	return _u
}

// ClearNormalizedEventID clears the value of the "normalized_event_id" field.
func (_u *KnowledgeFactHistoryUpdate) ClearNormalizedEventID() *KnowledgeFactHistoryUpdate {
	_u.mutation.ClearNormalizedEventID()
	return _u
}

// SetEventKind sets the "event_kind" field.
func (_u *KnowledgeFactHistoryUpdate) SetEventKind(v string) *KnowledgeFactHistoryUpdate {
	_u.mutation.SetEventKind(v)
	return _u
}

// SetNillableEventKind sets the "event_kind" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdate) SetNillableEventKind(v *string) *KnowledgeFactHistoryUpdate {
	if v != nil {
		_u.SetEventKind(*v)
	}
	return _u
}

// SetHistoryKey sets the "history_key" field.
func (_u *KnowledgeFactHistoryUpdate) SetHistoryKey(v string) *KnowledgeFactHistoryUpdate {
	_u.mutation.SetHistoryKey(v)
	return _u
}

// SetNillableHistoryKey sets the "history_key" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdate) SetNillableHistoryKey(v *string) *KnowledgeFactHistoryUpdate {
	if v != nil {
		_u.SetHistoryKey(*v)
	}
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *KnowledgeFactHistoryUpdate) SetOccurredAt(v time.Time) *KnowledgeFactHistoryUpdate {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdate) SetNillableOccurredAt(v *time.Time) *KnowledgeFactHistoryUpdate {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetRecordedAt sets the "recorded_at" field.
func (_u *KnowledgeFactHistoryUpdate) SetRecordedAt(v time.Time) *KnowledgeFactHistoryUpdate {
	_u.mutation.SetRecordedAt(v)
	return _u
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdate) SetNillableRecordedAt(v *time.Time) *KnowledgeFactHistoryUpdate {
	if v != nil {
		_u.SetRecordedAt(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *KnowledgeFactHistoryUpdate) SetProvider(v string) *KnowledgeFactHistoryUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdate) SetNillableProvider(v *string) *KnowledgeFactHistoryUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderSource sets the "provider_source" field.
func (_u *KnowledgeFactHistoryUpdate) SetProviderSource(v string) *KnowledgeFactHistoryUpdate {
	_u.mutation.SetProviderSource(v)
	return _u
}

// SetNillableProviderSource sets the "provider_source" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdate) SetNillableProviderSource(v *string) *KnowledgeFactHistoryUpdate {
	if v != nil {
		_u.SetProviderSource(*v)
	}
	return _u
}

// SetProviderEventRef sets the "provider_event_ref" field.
func (_u *KnowledgeFactHistoryUpdate) SetProviderEventRef(v string) *KnowledgeFactHistoryUpdate {
	_u.mutation.SetProviderEventRef(v)
	return _u
}

// SetNillableProviderEventRef sets the "provider_event_ref" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdate) SetNillableProviderEventRef(v *string) *KnowledgeFactHistoryUpdate {
	if v != nil {
		_u.SetProviderEventRef(*v)
	}
	return _u
}

// SetExtractionMethod sets the "extraction_method" field.
func (_u *KnowledgeFactHistoryUpdate) SetExtractionMethod(v string) *KnowledgeFactHistoryUpdate {
	_u.mutation.SetExtractionMethod(v)
	return _u
}

// SetNillableExtractionMethod sets the "extraction_method" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdate) SetNillableExtractionMethod(v *string) *KnowledgeFactHistoryUpdate {
	if v != nil {
		_u.SetExtractionMethod(*v)
	}
	return _u
}

// SetAttributes sets the "attributes" field.
func (_u *KnowledgeFactHistoryUpdate) SetAttributes(v map[string]interface{}) *KnowledgeFactHistoryUpdate {
	_u.mutation.SetAttributes(v)
	return _u
}

// ClearAttributes clears the value of the "attributes" field.
func (_u *KnowledgeFactHistoryUpdate) ClearAttributes() *KnowledgeFactHistoryUpdate {
	_u.mutation.ClearAttributes()
	return _u
}

// SetAlias sets the "alias" edge to the KnowledgeEntityAlias entity.
func (_u *KnowledgeFactHistoryUpdate) SetAlias(v *KnowledgeEntityAlias) *KnowledgeFactHistoryUpdate {
	return _u.SetAliasID(v.ID)
}

// SetRelationship sets the "relationship" edge to the KnowledgeRelationship entity.
func (_u *KnowledgeFactHistoryUpdate) SetRelationship(v *KnowledgeRelationship) *KnowledgeFactHistoryUpdate {
	return _u.SetRelationshipID(v.ID)
}

// SetNormalizedEvent sets the "normalized_event" edge to the NormalizedEvent entity.
func (_u *KnowledgeFactHistoryUpdate) SetNormalizedEvent(v *NormalizedEvent) *KnowledgeFactHistoryUpdate {
	return _u.SetNormalizedEventID(v.ID)
}

// Mutation returns the KnowledgeFactHistoryMutation object of the builder.
func (_u *KnowledgeFactHistoryUpdate) Mutation() *KnowledgeFactHistoryMutation {
	return _u.mutation
}

// ClearAlias clears the "alias" edge to the KnowledgeEntityAlias entity.
func (_u *KnowledgeFactHistoryUpdate) ClearAlias() *KnowledgeFactHistoryUpdate {
	_u.mutation.ClearAlias()
	return _u
}

// ClearRelationship clears the "relationship" edge to the KnowledgeRelationship entity.
func (_u *KnowledgeFactHistoryUpdate) ClearRelationship() *KnowledgeFactHistoryUpdate {
	_u.mutation.ClearRelationship()
	return _u
}

// ClearNormalizedEvent clears the "normalized_event" edge to the NormalizedEvent entity.
func (_u *KnowledgeFactHistoryUpdate) ClearNormalizedEvent() *KnowledgeFactHistoryUpdate {
	_u.mutation.ClearNormalizedEvent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KnowledgeFactHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeFactHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KnowledgeFactHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeFactHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeFactHistoryUpdate) check() error {
	if v, ok := _u.mutation.FactKind(); ok {
		if err := knowledgefacthistory.FactKindValidator(v); err != nil {
			return &ValidationError{Name: "fact_kind", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.fact_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventKind(); ok {
		if err := knowledgefacthistory.EventKindValidator(v); err != nil {
			return &ValidationError{Name: "event_kind", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.event_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HistoryKey(); ok {
		if err := knowledgefacthistory.HistoryKeyValidator(v); err != nil {
			return &ValidationError{Name: "history_key", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.history_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := knowledgefacthistory.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderSource(); ok {
		if err := knowledgefacthistory.ProviderSourceValidator(v); err != nil {
			return &ValidationError{Name: "provider_source", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.provider_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderEventRef(); ok {
		if err := knowledgefacthistory.ProviderEventRefValidator(v); err != nil {
			return &ValidationError{Name: "provider_event_ref", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.provider_event_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExtractionMethod(); ok {
		if err := knowledgefacthistory.ExtractionMethodValidator(v); err != nil {
			return &ValidationError{Name: "extraction_method", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.extraction_method": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "KnowledgeFactHistory.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *KnowledgeFactHistoryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KnowledgeFactHistoryUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *KnowledgeFactHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgefacthistory.Table, knowledgefacthistory.Columns, sqlgraph.NewFieldSpec(knowledgefacthistory.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FactKind(); ok {
		_spec.SetField(knowledgefacthistory.FieldFactKind, field.TypeEnum, value)
	}
	if _u.mutation.FactKindCleared() {
		_spec.ClearField(knowledgefacthistory.FieldFactKind, field.TypeEnum)
	}
	if value, ok := _u.mutation.EventKind(); ok {
		_spec.SetField(knowledgefacthistory.FieldEventKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.HistoryKey(); ok {
		_spec.SetField(knowledgefacthistory.FieldHistoryKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(knowledgefacthistory.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RecordedAt(); ok {
		_spec.SetField(knowledgefacthistory.FieldRecordedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(knowledgefacthistory.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderSource(); ok {
		_spec.SetField(knowledgefacthistory.FieldProviderSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderEventRef(); ok {
		_spec.SetField(knowledgefacthistory.FieldProviderEventRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExtractionMethod(); ok {
		_spec.SetField(knowledgefacthistory.FieldExtractionMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attributes(); ok {
		_spec.SetField(knowledgefacthistory.FieldAttributes, field.TypeJSON, value)
	}
	if _u.mutation.AttributesCleared() {
		_spec.ClearField(knowledgefacthistory.FieldAttributes, field.TypeJSON)
	}
	if _u.mutation.AliasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgefacthistory.AliasTable,
			Columns: []string{knowledgefacthistory.AliasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgeentityalias.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.KnowledgeFactHistory
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AliasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgefacthistory.AliasTable,
			Columns: []string{knowledgefacthistory.AliasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgeentityalias.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.KnowledgeFactHistory
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RelationshipCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgefacthistory.RelationshipTable,
			Columns: []string{knowledgefacthistory.RelationshipColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgerelationship.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.KnowledgeFactHistory
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RelationshipIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgefacthistory.RelationshipTable,
			Columns: []string{knowledgefacthistory.RelationshipColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgerelationship.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.KnowledgeFactHistory
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NormalizedEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgefacthistory.NormalizedEventTable,
			Columns: []string{knowledgefacthistory.NormalizedEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(normalizedevent.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.KnowledgeFactHistory
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NormalizedEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgefacthistory.NormalizedEventTable,
			Columns: []string{knowledgefacthistory.NormalizedEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(normalizedevent.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.KnowledgeFactHistory
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.KnowledgeFactHistory
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgefacthistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KnowledgeFactHistoryUpdateOne is the builder for updating a single KnowledgeFactHistory entity.
type KnowledgeFactHistoryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *KnowledgeFactHistoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetFactKind sets the "fact_kind" field.
func (_u *KnowledgeFactHistoryUpdateOne) SetFactKind(v knowledgefacthistory.FactKind) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.SetFactKind(v)
	return _u
}

// SetNillableFactKind sets the "fact_kind" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdateOne) SetNillableFactKind(v *knowledgefacthistory.FactKind) *KnowledgeFactHistoryUpdateOne {
	if v != nil {
		_u.SetFactKind(*v)
	}
	return _u
}

// ClearFactKind clears the value of the "fact_kind" field.
func (_u *KnowledgeFactHistoryUpdateOne) ClearFactKind() *KnowledgeFactHistoryUpdateOne {
	_u.mutation.ClearFactKind()
	return _u
}

// SetAliasID sets the "alias_id" field.
func (_u *KnowledgeFactHistoryUpdateOne) SetAliasID(v uuid.UUID) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.SetAliasID(v)
	return _u
}

// SetNillableAliasID sets the "alias_id" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdateOne) SetNillableAliasID(v *uuid.UUID) *KnowledgeFactHistoryUpdateOne {
	if v != nil {
		_u.SetAliasID(*v)
	}
	return _u
}

// ClearAliasID clears the value of the "alias_id" field.
func (_u *KnowledgeFactHistoryUpdateOne) ClearAliasID() *KnowledgeFactHistoryUpdateOne {
	_u.mutation.ClearAliasID()
	return _u
}

// SetRelationshipID sets the "relationship_id" field.
func (_u *KnowledgeFactHistoryUpdateOne) SetRelationshipID(v uuid.UUID) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.SetRelationshipID(v)
	return _u
}

// SetNillableRelationshipID sets the "relationship_id" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdateOne) SetNillableRelationshipID(v *uuid.UUID) *KnowledgeFactHistoryUpdateOne {
	if v != nil {
		_u.SetRelationshipID(*v)
	}
	return _u
}

// ClearRelationshipID clears the value of the "relationship_id" field.
func (_u *KnowledgeFactHistoryUpdateOne) ClearRelationshipID() *KnowledgeFactHistoryUpdateOne {
	_u.mutation.ClearRelationshipID()
	return _u
}

// SetNormalizedEventID sets the "normalized_event_id" field.
func (_u *KnowledgeFactHistoryUpdateOne) SetNormalizedEventID(v uuid.UUID) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.SetNormalizedEventID(v)
	return _u
}

// SetNillableNormalizedEventID sets the "normalized_event_id" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdateOne) SetNillableNormalizedEventID(v *uuid.UUID) *KnowledgeFactHistoryUpdateOne {
	if v != nil {
		_u.SetNormalizedEventID(*v)
	}
	return _u
}

// ClearNormalizedEventID clears the value of the "normalized_event_id" field.
func (_u *KnowledgeFactHistoryUpdateOne) ClearNormalizedEventID() *KnowledgeFactHistoryUpdateOne {
	_u.mutation.ClearNormalizedEventID()
	return _u
}

// SetEventKind sets the "event_kind" field.
func (_u *KnowledgeFactHistoryUpdateOne) SetEventKind(v string) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.SetEventKind(v)
	return _u
}

// SetNillableEventKind sets the "event_kind" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdateOne) SetNillableEventKind(v *string) *KnowledgeFactHistoryUpdateOne {
	if v != nil {
		_u.SetEventKind(*v)
	}
	return _u
}

// SetHistoryKey sets the "history_key" field.
func (_u *KnowledgeFactHistoryUpdateOne) SetHistoryKey(v string) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.SetHistoryKey(v)
	return _u
}

// SetNillableHistoryKey sets the "history_key" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdateOne) SetNillableHistoryKey(v *string) *KnowledgeFactHistoryUpdateOne {
	if v != nil {
		_u.SetHistoryKey(*v)
	}
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *KnowledgeFactHistoryUpdateOne) SetOccurredAt(v time.Time) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdateOne) SetNillableOccurredAt(v *time.Time) *KnowledgeFactHistoryUpdateOne {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetRecordedAt sets the "recorded_at" field.
func (_u *KnowledgeFactHistoryUpdateOne) SetRecordedAt(v time.Time) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.SetRecordedAt(v)
	return _u
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdateOne) SetNillableRecordedAt(v *time.Time) *KnowledgeFactHistoryUpdateOne {
	if v != nil {
		_u.SetRecordedAt(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *KnowledgeFactHistoryUpdateOne) SetProvider(v string) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdateOne) SetNillableProvider(v *string) *KnowledgeFactHistoryUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderSource sets the "provider_source" field.
func (_u *KnowledgeFactHistoryUpdateOne) SetProviderSource(v string) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.SetProviderSource(v)
	return _u
}

// SetNillableProviderSource sets the "provider_source" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdateOne) SetNillableProviderSource(v *string) *KnowledgeFactHistoryUpdateOne {
	if v != nil {
		_u.SetProviderSource(*v)
	}
	return _u
}

// SetProviderEventRef sets the "provider_event_ref" field.
func (_u *KnowledgeFactHistoryUpdateOne) SetProviderEventRef(v string) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.SetProviderEventRef(v)
	return _u
}

// SetNillableProviderEventRef sets the "provider_event_ref" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdateOne) SetNillableProviderEventRef(v *string) *KnowledgeFactHistoryUpdateOne {
	if v != nil {
		_u.SetProviderEventRef(*v)
	}
	return _u
}

// SetExtractionMethod sets the "extraction_method" field.
func (_u *KnowledgeFactHistoryUpdateOne) SetExtractionMethod(v string) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.SetExtractionMethod(v)
	return _u
}

// SetNillableExtractionMethod sets the "extraction_method" field if the given value is not nil.
func (_u *KnowledgeFactHistoryUpdateOne) SetNillableExtractionMethod(v *string) *KnowledgeFactHistoryUpdateOne {
	if v != nil {
		_u.SetExtractionMethod(*v)
	}
	return _u
}

// SetAttributes sets the "attributes" field.
func (_u *KnowledgeFactHistoryUpdateOne) SetAttributes(v map[string]interface{}) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.SetAttributes(v)
	return _u
}

// ClearAttributes clears the value of the "attributes" field.
func (_u *KnowledgeFactHistoryUpdateOne) ClearAttributes() *KnowledgeFactHistoryUpdateOne {
	_u.mutation.ClearAttributes()
	return _u
}

// SetAlias sets the "alias" edge to the KnowledgeEntityAlias entity.
func (_u *KnowledgeFactHistoryUpdateOne) SetAlias(v *KnowledgeEntityAlias) *KnowledgeFactHistoryUpdateOne {
	return _u.SetAliasID(v.ID)
}

// SetRelationship sets the "relationship" edge to the KnowledgeRelationship entity.
func (_u *KnowledgeFactHistoryUpdateOne) SetRelationship(v *KnowledgeRelationship) *KnowledgeFactHistoryUpdateOne {
	return _u.SetRelationshipID(v.ID)
}

// SetNormalizedEvent sets the "normalized_event" edge to the NormalizedEvent entity.
func (_u *KnowledgeFactHistoryUpdateOne) SetNormalizedEvent(v *NormalizedEvent) *KnowledgeFactHistoryUpdateOne {
	return _u.SetNormalizedEventID(v.ID)
}

// Mutation returns the KnowledgeFactHistoryMutation object of the builder.
func (_u *KnowledgeFactHistoryUpdateOne) Mutation() *KnowledgeFactHistoryMutation {
	return _u.mutation
}

// ClearAlias clears the "alias" edge to the KnowledgeEntityAlias entity.
func (_u *KnowledgeFactHistoryUpdateOne) ClearAlias() *KnowledgeFactHistoryUpdateOne {
	_u.mutation.ClearAlias()
	return _u
}

// ClearRelationship clears the "relationship" edge to the KnowledgeRelationship entity.
func (_u *KnowledgeFactHistoryUpdateOne) ClearRelationship() *KnowledgeFactHistoryUpdateOne {
	_u.mutation.ClearRelationship()
	return _u
}

// ClearNormalizedEvent clears the "normalized_event" edge to the NormalizedEvent entity.
func (_u *KnowledgeFactHistoryUpdateOne) ClearNormalizedEvent() *KnowledgeFactHistoryUpdateOne {
	_u.mutation.ClearNormalizedEvent()
	return _u
}

// Where appends a list predicates to the KnowledgeFactHistoryUpdate builder.
func (_u *KnowledgeFactHistoryUpdateOne) Where(ps ...predicate.KnowledgeFactHistory) *KnowledgeFactHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KnowledgeFactHistoryUpdateOne) Select(field string, fields ...string) *KnowledgeFactHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KnowledgeFactHistory entity.
func (_u *KnowledgeFactHistoryUpdateOne) Save(ctx context.Context) (*KnowledgeFactHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeFactHistoryUpdateOne) SaveX(ctx context.Context) *KnowledgeFactHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KnowledgeFactHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeFactHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeFactHistoryUpdateOne) check() error {
	if v, ok := _u.mutation.FactKind(); ok {
		if err := knowledgefacthistory.FactKindValidator(v); err != nil {
			return &ValidationError{Name: "fact_kind", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.fact_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventKind(); ok {
		if err := knowledgefacthistory.EventKindValidator(v); err != nil {
			return &ValidationError{Name: "event_kind", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.event_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HistoryKey(); ok {
		if err := knowledgefacthistory.HistoryKeyValidator(v); err != nil {
			return &ValidationError{Name: "history_key", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.history_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := knowledgefacthistory.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderSource(); ok {
		if err := knowledgefacthistory.ProviderSourceValidator(v); err != nil {
			return &ValidationError{Name: "provider_source", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.provider_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderEventRef(); ok {
		if err := knowledgefacthistory.ProviderEventRefValidator(v); err != nil {
			return &ValidationError{Name: "provider_event_ref", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.provider_event_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExtractionMethod(); ok {
		if err := knowledgefacthistory.ExtractionMethodValidator(v); err != nil {
			return &ValidationError{Name: "extraction_method", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFactHistory.extraction_method": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "KnowledgeFactHistory.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *KnowledgeFactHistoryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KnowledgeFactHistoryUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *KnowledgeFactHistoryUpdateOne) sqlSave(ctx context.Context) (_node *KnowledgeFactHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgefacthistory.Table, knowledgefacthistory.Columns, sqlgraph.NewFieldSpec(knowledgefacthistory.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KnowledgeFactHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, knowledgefacthistory.FieldID)
		for _, f := range fields {
			if !knowledgefacthistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != knowledgefacthistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FactKind(); ok {
		_spec.SetField(knowledgefacthistory.FieldFactKind, field.TypeEnum, value)
	}
	if _u.mutation.FactKindCleared() {
		_spec.ClearField(knowledgefacthistory.FieldFactKind, field.TypeEnum)
	}
	if value, ok := _u.mutation.EventKind(); ok {
		_spec.SetField(knowledgefacthistory.FieldEventKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.HistoryKey(); ok {
		_spec.SetField(knowledgefacthistory.FieldHistoryKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(knowledgefacthistory.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RecordedAt(); ok {
		_spec.SetField(knowledgefacthistory.FieldRecordedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(knowledgefacthistory.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderSource(); ok {
		_spec.SetField(knowledgefacthistory.FieldProviderSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderEventRef(); ok {
		_spec.SetField(knowledgefacthistory.FieldProviderEventRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExtractionMethod(); ok {
		_spec.SetField(knowledgefacthistory.FieldExtractionMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attributes(); ok {
		_spec.SetField(knowledgefacthistory.FieldAttributes, field.TypeJSON, value)
	}
	if _u.mutation.AttributesCleared() {
		_spec.ClearField(knowledgefacthistory.FieldAttributes, field.TypeJSON)
	}
	if _u.mutation.AliasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgefacthistory.AliasTable,
			Columns: []string{knowledgefacthistory.AliasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgeentityalias.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.KnowledgeFactHistory
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AliasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgefacthistory.AliasTable,
			Columns: []string{knowledgefacthistory.AliasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgeentityalias.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.KnowledgeFactHistory
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RelationshipCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgefacthistory.RelationshipTable,
			Columns: []string{knowledgefacthistory.RelationshipColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgerelationship.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.KnowledgeFactHistory
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RelationshipIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgefacthistory.RelationshipTable,
			Columns: []string{knowledgefacthistory.RelationshipColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgerelationship.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.KnowledgeFactHistory
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NormalizedEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgefacthistory.NormalizedEventTable,
			Columns: []string{knowledgefacthistory.NormalizedEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(normalizedevent.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.KnowledgeFactHistory
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NormalizedEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgefacthistory.NormalizedEventTable,
			Columns: []string{knowledgefacthistory.NormalizedEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(normalizedevent.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.KnowledgeFactHistory
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.KnowledgeFactHistory
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	_node = &KnowledgeFactHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgefacthistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
