// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rezible/rezible/ent/internal"
	"github.com/rezible/rezible/ent/predicate"
	"github.com/rezible/rezible/ent/systemanalysisentry"
)

// SystemAnalysisEntryDelete is the builder for deleting a SystemAnalysisEntry entity.
type SystemAnalysisEntryDelete struct {
	config
	hooks    []Hook
	mutation *SystemAnalysisEntryMutation
}

// Where appends a list predicates to the SystemAnalysisEntryDelete builder.
func (_d *SystemAnalysisEntryDelete) Where(ps ...predicate.SystemAnalysisEntry) *SystemAnalysisEntryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SystemAnalysisEntryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SystemAnalysisEntryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SystemAnalysisEntryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(systemanalysisentry.Table, sqlgraph.NewFieldSpec(systemanalysisentry.FieldID, field.TypeUUID))
	_spec.Node.Schema = _d.schemaConfig.SystemAnalysisEntry
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SystemAnalysisEntryDeleteOne is the builder for deleting a single SystemAnalysisEntry entity.
type SystemAnalysisEntryDeleteOne struct {
	_d *SystemAnalysisEntryDelete
}

// Where appends a list predicates to the SystemAnalysisEntryDelete builder.
func (_d *SystemAnalysisEntryDeleteOne) Where(ps ...predicate.SystemAnalysisEntry) *SystemAnalysisEntryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SystemAnalysisEntryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{systemanalysisentry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SystemAnalysisEntryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
