// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rezible/rezible/ent/internal"
	"github.com/rezible/rezible/ent/predicate"
	"github.com/rezible/rezible/ent/systemanalysisentity"
)

// SystemAnalysisEntityUpdate is the builder for updating SystemAnalysisEntity entities.
type SystemAnalysisEntityUpdate struct {
	config
	hooks     []Hook
	mutation  *SystemAnalysisEntityMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SystemAnalysisEntityUpdate builder.
func (_u *SystemAnalysisEntityUpdate) Where(ps ...predicate.SystemAnalysisEntity) *SystemAnalysisEntityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SystemAnalysisEntityUpdate) SetCreatedAt(v time.Time) *SystemAnalysisEntityUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SystemAnalysisEntityUpdate) SetNillableCreatedAt(v *time.Time) *SystemAnalysisEntityUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemAnalysisEntityUpdate) SetUpdatedAt(v time.Time) *SystemAnalysisEntityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPosX sets the "pos_x" field.
func (_u *SystemAnalysisEntityUpdate) SetPosX(v float64) *SystemAnalysisEntityUpdate {
	_u.mutation.ResetPosX()
	_u.mutation.SetPosX(v)
	return _u
}

// SetNillablePosX sets the "pos_x" field if the given value is not nil.
func (_u *SystemAnalysisEntityUpdate) SetNillablePosX(v *float64) *SystemAnalysisEntityUpdate {
	if v != nil {
		_u.SetPosX(*v)
	}
	return _u
}

// AddPosX adds value to the "pos_x" field.
func (_u *SystemAnalysisEntityUpdate) AddPosX(v float64) *SystemAnalysisEntityUpdate {
	_u.mutation.AddPosX(v)
	return _u
}

// ClearPosX clears the value of the "pos_x" field.
func (_u *SystemAnalysisEntityUpdate) ClearPosX() *SystemAnalysisEntityUpdate {
	_u.mutation.ClearPosX()
	return _u
}

// SetPosY sets the "pos_y" field.
func (_u *SystemAnalysisEntityUpdate) SetPosY(v float64) *SystemAnalysisEntityUpdate {
	_u.mutation.ResetPosY()
	_u.mutation.SetPosY(v)
	return _u
}

// SetNillablePosY sets the "pos_y" field if the given value is not nil.
func (_u *SystemAnalysisEntityUpdate) SetNillablePosY(v *float64) *SystemAnalysisEntityUpdate {
	if v != nil {
		_u.SetPosY(*v)
	}
	return _u
}

// AddPosY adds value to the "pos_y" field.
func (_u *SystemAnalysisEntityUpdate) AddPosY(v float64) *SystemAnalysisEntityUpdate {
	_u.mutation.AddPosY(v)
	return _u
}

// ClearPosY clears the value of the "pos_y" field.
func (_u *SystemAnalysisEntityUpdate) ClearPosY() *SystemAnalysisEntityUpdate {
	_u.mutation.ClearPosY()
	return _u
}

// SetHidden sets the "hidden" field.
func (_u *SystemAnalysisEntityUpdate) SetHidden(v bool) *SystemAnalysisEntityUpdate {
	_u.mutation.SetHidden(v)
	return _u
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (_u *SystemAnalysisEntityUpdate) SetNillableHidden(v *bool) *SystemAnalysisEntityUpdate {
	if v != nil {
		_u.SetHidden(*v)
	}
	return _u
}

// SetLabelOverride sets the "label_override" field.
func (_u *SystemAnalysisEntityUpdate) SetLabelOverride(v string) *SystemAnalysisEntityUpdate {
	_u.mutation.SetLabelOverride(v)
	return _u
}

// SetNillableLabelOverride sets the "label_override" field if the given value is not nil.
func (_u *SystemAnalysisEntityUpdate) SetNillableLabelOverride(v *string) *SystemAnalysisEntityUpdate {
	if v != nil {
		_u.SetLabelOverride(*v)
	}
	return _u
}

// ClearLabelOverride clears the value of the "label_override" field.
func (_u *SystemAnalysisEntityUpdate) ClearLabelOverride() *SystemAnalysisEntityUpdate {
	_u.mutation.ClearLabelOverride()
	return _u
}

// SetDescriptionOverride sets the "description_override" field.
func (_u *SystemAnalysisEntityUpdate) SetDescriptionOverride(v string) *SystemAnalysisEntityUpdate {
	_u.mutation.SetDescriptionOverride(v)
	return _u
}

// SetNillableDescriptionOverride sets the "description_override" field if the given value is not nil.
func (_u *SystemAnalysisEntityUpdate) SetNillableDescriptionOverride(v *string) *SystemAnalysisEntityUpdate {
	if v != nil {
		_u.SetDescriptionOverride(*v)
	}
	return _u
}

// ClearDescriptionOverride clears the value of the "description_override" field.
func (_u *SystemAnalysisEntityUpdate) ClearDescriptionOverride() *SystemAnalysisEntityUpdate {
	_u.mutation.ClearDescriptionOverride()
	return _u
}

// SetProperties sets the "properties" field.
func (_u *SystemAnalysisEntityUpdate) SetProperties(v map[string]interface{}) *SystemAnalysisEntityUpdate {
	_u.mutation.SetProperties(v)
	return _u
}

// ClearProperties clears the value of the "properties" field.
func (_u *SystemAnalysisEntityUpdate) ClearProperties() *SystemAnalysisEntityUpdate {
	_u.mutation.ClearProperties()
	return _u
}

// Mutation returns the SystemAnalysisEntityMutation object of the builder.
func (_u *SystemAnalysisEntityUpdate) Mutation() *SystemAnalysisEntityMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemAnalysisEntityUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemAnalysisEntityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemAnalysisEntityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemAnalysisEntityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemAnalysisEntityUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if systemanalysisentity.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized systemanalysisentity.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := systemanalysisentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemAnalysisEntityUpdate) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemAnalysisEntity.tenant"`)
	}
	if _u.mutation.AnalysisCleared() && len(_u.mutation.AnalysisIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemAnalysisEntity.analysis"`)
	}
	if _u.mutation.KnowledgeEntityCleared() && len(_u.mutation.KnowledgeEntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemAnalysisEntity.knowledge_entity"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SystemAnalysisEntityUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SystemAnalysisEntityUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SystemAnalysisEntityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemanalysisentity.Table, systemanalysisentity.Columns, sqlgraph.NewFieldSpec(systemanalysisentity.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(systemanalysisentity.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemanalysisentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PosX(); ok {
		_spec.SetField(systemanalysisentity.FieldPosX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPosX(); ok {
		_spec.AddField(systemanalysisentity.FieldPosX, field.TypeFloat64, value)
	}
	if _u.mutation.PosXCleared() {
		_spec.ClearField(systemanalysisentity.FieldPosX, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PosY(); ok {
		_spec.SetField(systemanalysisentity.FieldPosY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPosY(); ok {
		_spec.AddField(systemanalysisentity.FieldPosY, field.TypeFloat64, value)
	}
	if _u.mutation.PosYCleared() {
		_spec.ClearField(systemanalysisentity.FieldPosY, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Hidden(); ok {
		_spec.SetField(systemanalysisentity.FieldHidden, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LabelOverride(); ok {
		_spec.SetField(systemanalysisentity.FieldLabelOverride, field.TypeString, value)
	}
	if _u.mutation.LabelOverrideCleared() {
		_spec.ClearField(systemanalysisentity.FieldLabelOverride, field.TypeString)
	}
	if value, ok := _u.mutation.DescriptionOverride(); ok {
		_spec.SetField(systemanalysisentity.FieldDescriptionOverride, field.TypeString, value)
	}
	if _u.mutation.DescriptionOverrideCleared() {
		_spec.ClearField(systemanalysisentity.FieldDescriptionOverride, field.TypeString)
	}
	if value, ok := _u.mutation.Properties(); ok {
		_spec.SetField(systemanalysisentity.FieldProperties, field.TypeJSON, value)
	}
	if _u.mutation.PropertiesCleared() {
		_spec.ClearField(systemanalysisentity.FieldProperties, field.TypeJSON)
	}
	_spec.Node.Schema = _u.schemaConfig.SystemAnalysisEntity
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemanalysisentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemAnalysisEntityUpdateOne is the builder for updating a single SystemAnalysisEntity entity.
type SystemAnalysisEntityUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SystemAnalysisEntityMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedAt sets the "created_at" field.
func (_u *SystemAnalysisEntityUpdateOne) SetCreatedAt(v time.Time) *SystemAnalysisEntityUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SystemAnalysisEntityUpdateOne) SetNillableCreatedAt(v *time.Time) *SystemAnalysisEntityUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemAnalysisEntityUpdateOne) SetUpdatedAt(v time.Time) *SystemAnalysisEntityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPosX sets the "pos_x" field.
func (_u *SystemAnalysisEntityUpdateOne) SetPosX(v float64) *SystemAnalysisEntityUpdateOne {
	_u.mutation.ResetPosX()
	_u.mutation.SetPosX(v)
	return _u
}

// SetNillablePosX sets the "pos_x" field if the given value is not nil.
func (_u *SystemAnalysisEntityUpdateOne) SetNillablePosX(v *float64) *SystemAnalysisEntityUpdateOne {
	if v != nil {
		_u.SetPosX(*v)
	}
	return _u
}

// AddPosX adds value to the "pos_x" field.
func (_u *SystemAnalysisEntityUpdateOne) AddPosX(v float64) *SystemAnalysisEntityUpdateOne {
	_u.mutation.AddPosX(v)
	return _u
}

// ClearPosX clears the value of the "pos_x" field.
func (_u *SystemAnalysisEntityUpdateOne) ClearPosX() *SystemAnalysisEntityUpdateOne {
	_u.mutation.ClearPosX()
	return _u
}

// SetPosY sets the "pos_y" field.
func (_u *SystemAnalysisEntityUpdateOne) SetPosY(v float64) *SystemAnalysisEntityUpdateOne {
	_u.mutation.ResetPosY()
	_u.mutation.SetPosY(v)
	return _u
}

// SetNillablePosY sets the "pos_y" field if the given value is not nil.
func (_u *SystemAnalysisEntityUpdateOne) SetNillablePosY(v *float64) *SystemAnalysisEntityUpdateOne {
	if v != nil {
		_u.SetPosY(*v)
	}
	return _u
}

// AddPosY adds value to the "pos_y" field.
func (_u *SystemAnalysisEntityUpdateOne) AddPosY(v float64) *SystemAnalysisEntityUpdateOne {
	_u.mutation.AddPosY(v)
	return _u
}

// ClearPosY clears the value of the "pos_y" field.
func (_u *SystemAnalysisEntityUpdateOne) ClearPosY() *SystemAnalysisEntityUpdateOne {
	_u.mutation.ClearPosY()
	return _u
}

// SetHidden sets the "hidden" field.
func (_u *SystemAnalysisEntityUpdateOne) SetHidden(v bool) *SystemAnalysisEntityUpdateOne {
	_u.mutation.SetHidden(v)
	return _u
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (_u *SystemAnalysisEntityUpdateOne) SetNillableHidden(v *bool) *SystemAnalysisEntityUpdateOne {
	if v != nil {
		_u.SetHidden(*v)
	}
	return _u
}

// SetLabelOverride sets the "label_override" field.
func (_u *SystemAnalysisEntityUpdateOne) SetLabelOverride(v string) *SystemAnalysisEntityUpdateOne {
	_u.mutation.SetLabelOverride(v)
	return _u
}

// SetNillableLabelOverride sets the "label_override" field if the given value is not nil.
func (_u *SystemAnalysisEntityUpdateOne) SetNillableLabelOverride(v *string) *SystemAnalysisEntityUpdateOne {
	if v != nil {
		_u.SetLabelOverride(*v)
	}
	return _u
}

// ClearLabelOverride clears the value of the "label_override" field.
func (_u *SystemAnalysisEntityUpdateOne) ClearLabelOverride() *SystemAnalysisEntityUpdateOne {
	_u.mutation.ClearLabelOverride()
	return _u
}

// SetDescriptionOverride sets the "description_override" field.
func (_u *SystemAnalysisEntityUpdateOne) SetDescriptionOverride(v string) *SystemAnalysisEntityUpdateOne {
	_u.mutation.SetDescriptionOverride(v)
	return _u
}

// SetNillableDescriptionOverride sets the "description_override" field if the given value is not nil.
func (_u *SystemAnalysisEntityUpdateOne) SetNillableDescriptionOverride(v *string) *SystemAnalysisEntityUpdateOne {
	if v != nil {
		_u.SetDescriptionOverride(*v)
	}
	return _u
}

// ClearDescriptionOverride clears the value of the "description_override" field.
func (_u *SystemAnalysisEntityUpdateOne) ClearDescriptionOverride() *SystemAnalysisEntityUpdateOne {
	_u.mutation.ClearDescriptionOverride()
	return _u
}

// SetProperties sets the "properties" field.
func (_u *SystemAnalysisEntityUpdateOne) SetProperties(v map[string]interface{}) *SystemAnalysisEntityUpdateOne {
	_u.mutation.SetProperties(v)
	return _u
}

// ClearProperties clears the value of the "properties" field.
func (_u *SystemAnalysisEntityUpdateOne) ClearProperties() *SystemAnalysisEntityUpdateOne {
	_u.mutation.ClearProperties()
	return _u
}

// Mutation returns the SystemAnalysisEntityMutation object of the builder.
func (_u *SystemAnalysisEntityUpdateOne) Mutation() *SystemAnalysisEntityMutation {
	return _u.mutation
}

// Where appends a list predicates to the SystemAnalysisEntityUpdate builder.
func (_u *SystemAnalysisEntityUpdateOne) Where(ps ...predicate.SystemAnalysisEntity) *SystemAnalysisEntityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemAnalysisEntityUpdateOne) Select(field string, fields ...string) *SystemAnalysisEntityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemAnalysisEntity entity.
func (_u *SystemAnalysisEntityUpdateOne) Save(ctx context.Context) (*SystemAnalysisEntity, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemAnalysisEntityUpdateOne) SaveX(ctx context.Context) *SystemAnalysisEntity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemAnalysisEntityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemAnalysisEntityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemAnalysisEntityUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if systemanalysisentity.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized systemanalysisentity.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := systemanalysisentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemAnalysisEntityUpdateOne) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemAnalysisEntity.tenant"`)
	}
	if _u.mutation.AnalysisCleared() && len(_u.mutation.AnalysisIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemAnalysisEntity.analysis"`)
	}
	if _u.mutation.KnowledgeEntityCleared() && len(_u.mutation.KnowledgeEntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemAnalysisEntity.knowledge_entity"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SystemAnalysisEntityUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SystemAnalysisEntityUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SystemAnalysisEntityUpdateOne) sqlSave(ctx context.Context) (_node *SystemAnalysisEntity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemanalysisentity.Table, systemanalysisentity.Columns, sqlgraph.NewFieldSpec(systemanalysisentity.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemAnalysisEntity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemanalysisentity.FieldID)
		for _, f := range fields {
			if !systemanalysisentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemanalysisentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(systemanalysisentity.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemanalysisentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PosX(); ok {
		_spec.SetField(systemanalysisentity.FieldPosX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPosX(); ok {
		_spec.AddField(systemanalysisentity.FieldPosX, field.TypeFloat64, value)
	}
	if _u.mutation.PosXCleared() {
		_spec.ClearField(systemanalysisentity.FieldPosX, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PosY(); ok {
		_spec.SetField(systemanalysisentity.FieldPosY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPosY(); ok {
		_spec.AddField(systemanalysisentity.FieldPosY, field.TypeFloat64, value)
	}
	if _u.mutation.PosYCleared() {
		_spec.ClearField(systemanalysisentity.FieldPosY, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Hidden(); ok {
		_spec.SetField(systemanalysisentity.FieldHidden, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LabelOverride(); ok {
		_spec.SetField(systemanalysisentity.FieldLabelOverride, field.TypeString, value)
	}
	if _u.mutation.LabelOverrideCleared() {
		_spec.ClearField(systemanalysisentity.FieldLabelOverride, field.TypeString)
	}
	if value, ok := _u.mutation.DescriptionOverride(); ok {
		_spec.SetField(systemanalysisentity.FieldDescriptionOverride, field.TypeString, value)
	}
	if _u.mutation.DescriptionOverrideCleared() {
		_spec.ClearField(systemanalysisentity.FieldDescriptionOverride, field.TypeString)
	}
	if value, ok := _u.mutation.Properties(); ok {
		_spec.SetField(systemanalysisentity.FieldProperties, field.TypeJSON, value)
	}
	if _u.mutation.PropertiesCleared() {
		_spec.ClearField(systemanalysisentity.FieldProperties, field.TypeJSON)
	}
	_spec.Node.Schema = _u.schemaConfig.SystemAnalysisEntity
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	_node = &SystemAnalysisEntity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemanalysisentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
