// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/rezible/rezible/ent/knowledgeentity"
	"github.com/rezible/rezible/ent/systemanalysis"
	"github.com/rezible/rezible/ent/systemanalysisentity"
	"github.com/rezible/rezible/ent/tenant"
)

// SystemAnalysisEntityCreate is the builder for creating a SystemAnalysisEntity entity.
type SystemAnalysisEntityCreate struct {
	config
	mutation *SystemAnalysisEntityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *SystemAnalysisEntityCreate) SetTenantID(v int) *SystemAnalysisEntityCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SystemAnalysisEntityCreate) SetCreatedAt(v time.Time) *SystemAnalysisEntityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SystemAnalysisEntityCreate) SetNillableCreatedAt(v *time.Time) *SystemAnalysisEntityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SystemAnalysisEntityCreate) SetUpdatedAt(v time.Time) *SystemAnalysisEntityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SystemAnalysisEntityCreate) SetNillableUpdatedAt(v *time.Time) *SystemAnalysisEntityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAnalysisID sets the "analysis_id" field.
func (_c *SystemAnalysisEntityCreate) SetAnalysisID(v uuid.UUID) *SystemAnalysisEntityCreate {
	_c.mutation.SetAnalysisID(v)
	return _c
}

// SetKnowledgeEntityID sets the "knowledge_entity_id" field.
func (_c *SystemAnalysisEntityCreate) SetKnowledgeEntityID(v uuid.UUID) *SystemAnalysisEntityCreate {
	_c.mutation.SetKnowledgeEntityID(v)
	return _c
}

// SetPosX sets the "pos_x" field.
func (_c *SystemAnalysisEntityCreate) SetPosX(v float64) *SystemAnalysisEntityCreate {
	_c.mutation.SetPosX(v)
	return _c
}

// SetNillablePosX sets the "pos_x" field if the given value is not nil.
func (_c *SystemAnalysisEntityCreate) SetNillablePosX(v *float64) *SystemAnalysisEntityCreate {
	if v != nil {
		_c.SetPosX(*v)
	}
	return _c
}

// SetPosY sets the "pos_y" field.
func (_c *SystemAnalysisEntityCreate) SetPosY(v float64) *SystemAnalysisEntityCreate {
	_c.mutation.SetPosY(v)
	return _c
}

// SetNillablePosY sets the "pos_y" field if the given value is not nil.
func (_c *SystemAnalysisEntityCreate) SetNillablePosY(v *float64) *SystemAnalysisEntityCreate {
	if v != nil {
		_c.SetPosY(*v)
	}
	return _c
}

// SetHidden sets the "hidden" field.
func (_c *SystemAnalysisEntityCreate) SetHidden(v bool) *SystemAnalysisEntityCreate {
	_c.mutation.SetHidden(v)
	return _c
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (_c *SystemAnalysisEntityCreate) SetNillableHidden(v *bool) *SystemAnalysisEntityCreate {
	if v != nil {
		_c.SetHidden(*v)
	}
	return _c
}

// SetLabelOverride sets the "label_override" field.
func (_c *SystemAnalysisEntityCreate) SetLabelOverride(v string) *SystemAnalysisEntityCreate {
	_c.mutation.SetLabelOverride(v)
	return _c
}

// SetNillableLabelOverride sets the "label_override" field if the given value is not nil.
func (_c *SystemAnalysisEntityCreate) SetNillableLabelOverride(v *string) *SystemAnalysisEntityCreate {
	if v != nil {
		_c.SetLabelOverride(*v)
	}
	return _c
}

// SetDescriptionOverride sets the "description_override" field.
func (_c *SystemAnalysisEntityCreate) SetDescriptionOverride(v string) *SystemAnalysisEntityCreate {
	_c.mutation.SetDescriptionOverride(v)
	return _c
}

// SetNillableDescriptionOverride sets the "description_override" field if the given value is not nil.
func (_c *SystemAnalysisEntityCreate) SetNillableDescriptionOverride(v *string) *SystemAnalysisEntityCreate {
	if v != nil {
		_c.SetDescriptionOverride(*v)
	}
	return _c
}

// SetProperties sets the "properties" field.
func (_c *SystemAnalysisEntityCreate) SetProperties(v map[string]interface{}) *SystemAnalysisEntityCreate {
	_c.mutation.SetProperties(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SystemAnalysisEntityCreate) SetID(v uuid.UUID) *SystemAnalysisEntityCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SystemAnalysisEntityCreate) SetNillableID(v *uuid.UUID) *SystemAnalysisEntityCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *SystemAnalysisEntityCreate) SetTenant(v *Tenant) *SystemAnalysisEntityCreate {
	return _c.SetTenantID(v.ID)
}

// SetAnalysis sets the "analysis" edge to the SystemAnalysis entity.
func (_c *SystemAnalysisEntityCreate) SetAnalysis(v *SystemAnalysis) *SystemAnalysisEntityCreate {
	return _c.SetAnalysisID(v.ID)
}

// SetKnowledgeEntity sets the "knowledge_entity" edge to the KnowledgeEntity entity.
func (_c *SystemAnalysisEntityCreate) SetKnowledgeEntity(v *KnowledgeEntity) *SystemAnalysisEntityCreate {
	return _c.SetKnowledgeEntityID(v.ID)
}

// Mutation returns the SystemAnalysisEntityMutation object of the builder.
func (_c *SystemAnalysisEntityCreate) Mutation() *SystemAnalysisEntityMutation {
	return _c.mutation
}

// Save creates the SystemAnalysisEntity in the database.
func (_c *SystemAnalysisEntityCreate) Save(ctx context.Context) (*SystemAnalysisEntity, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SystemAnalysisEntityCreate) SaveX(ctx context.Context) *SystemAnalysisEntity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemAnalysisEntityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemAnalysisEntityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SystemAnalysisEntityCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if systemanalysisentity.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized systemanalysisentity.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := systemanalysisentity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if systemanalysisentity.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized systemanalysisentity.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := systemanalysisentity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Hidden(); !ok {
		v := systemanalysisentity.DefaultHidden
		_c.mutation.SetHidden(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if systemanalysisentity.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized systemanalysisentity.DefaultID (forgotten import ent/runtime?)")
		}
		v := systemanalysisentity.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SystemAnalysisEntityCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "SystemAnalysisEntity.tenant_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SystemAnalysisEntity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SystemAnalysisEntity.updated_at"`)}
	}
	if _, ok := _c.mutation.AnalysisID(); !ok {
		return &ValidationError{Name: "analysis_id", err: errors.New(`ent: missing required field "SystemAnalysisEntity.analysis_id"`)}
	}
	if _, ok := _c.mutation.KnowledgeEntityID(); !ok {
		return &ValidationError{Name: "knowledge_entity_id", err: errors.New(`ent: missing required field "SystemAnalysisEntity.knowledge_entity_id"`)}
	}
	if _, ok := _c.mutation.Hidden(); !ok {
		return &ValidationError{Name: "hidden", err: errors.New(`ent: missing required field "SystemAnalysisEntity.hidden"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "SystemAnalysisEntity.tenant"`)}
	}
	if len(_c.mutation.AnalysisIDs()) == 0 {
		return &ValidationError{Name: "analysis", err: errors.New(`ent: missing required edge "SystemAnalysisEntity.analysis"`)}
	}
	if len(_c.mutation.KnowledgeEntityIDs()) == 0 {
		return &ValidationError{Name: "knowledge_entity", err: errors.New(`ent: missing required edge "SystemAnalysisEntity.knowledge_entity"`)}
	}
	return nil
}

func (_c *SystemAnalysisEntityCreate) sqlSave(ctx context.Context) (*SystemAnalysisEntity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SystemAnalysisEntityCreate) createSpec() (*SystemAnalysisEntity, *sqlgraph.CreateSpec) {
	var (
		_node = &SystemAnalysisEntity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(systemanalysisentity.Table, sqlgraph.NewFieldSpec(systemanalysisentity.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.SystemAnalysisEntity
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(systemanalysisentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(systemanalysisentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PosX(); ok {
		_spec.SetField(systemanalysisentity.FieldPosX, field.TypeFloat64, value)
		_node.PosX = &value
	}
	if value, ok := _c.mutation.PosY(); ok {
		_spec.SetField(systemanalysisentity.FieldPosY, field.TypeFloat64, value)
		_node.PosY = &value
	}
	if value, ok := _c.mutation.Hidden(); ok {
		_spec.SetField(systemanalysisentity.FieldHidden, field.TypeBool, value)
		_node.Hidden = value
	}
	if value, ok := _c.mutation.LabelOverride(); ok {
		_spec.SetField(systemanalysisentity.FieldLabelOverride, field.TypeString, value)
		_node.LabelOverride = &value
	}
	if value, ok := _c.mutation.DescriptionOverride(); ok {
		_spec.SetField(systemanalysisentity.FieldDescriptionOverride, field.TypeString, value)
		_node.DescriptionOverride = &value
	}
	if value, ok := _c.mutation.Properties(); ok {
		_spec.SetField(systemanalysisentity.FieldProperties, field.TypeJSON, value)
		_node.Properties = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systemanalysisentity.TenantTable,
			Columns: []string{systemanalysisentity.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _c.schemaConfig.SystemAnalysisEntity
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnalysisIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systemanalysisentity.AnalysisTable,
			Columns: []string{systemanalysisentity.AnalysisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemanalysis.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.SystemAnalysisEntity
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AnalysisID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.KnowledgeEntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systemanalysisentity.KnowledgeEntityTable,
			Columns: []string{systemanalysisentity.KnowledgeEntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgeentity.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.SystemAnalysisEntity
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.KnowledgeEntityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SystemAnalysisEntity.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemAnalysisEntityUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemAnalysisEntityCreate) OnConflict(opts ...sql.ConflictOption) *SystemAnalysisEntityUpsertOne {
	_c.conflict = opts
	return &SystemAnalysisEntityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SystemAnalysisEntity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemAnalysisEntityCreate) OnConflictColumns(columns ...string) *SystemAnalysisEntityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemAnalysisEntityUpsertOne{
		create: _c,
	}
}

type (
	// SystemAnalysisEntityUpsertOne is the builder for "upsert"-ing
	//  one SystemAnalysisEntity node.
	SystemAnalysisEntityUpsertOne struct {
		create *SystemAnalysisEntityCreate
	}

	// SystemAnalysisEntityUpsert is the "OnConflict" setter.
	SystemAnalysisEntityUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *SystemAnalysisEntityUpsert) SetCreatedAt(v time.Time) *SystemAnalysisEntityUpsert {
	u.Set(systemanalysisentity.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsert) UpdateCreatedAt() *SystemAnalysisEntityUpsert {
	u.SetExcluded(systemanalysisentity.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemAnalysisEntityUpsert) SetUpdatedAt(v time.Time) *SystemAnalysisEntityUpsert {
	u.Set(systemanalysisentity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsert) UpdateUpdatedAt() *SystemAnalysisEntityUpsert {
	u.SetExcluded(systemanalysisentity.FieldUpdatedAt)
	return u
}

// SetPosX sets the "pos_x" field.
func (u *SystemAnalysisEntityUpsert) SetPosX(v float64) *SystemAnalysisEntityUpsert {
	u.Set(systemanalysisentity.FieldPosX, v)
	return u
}

// UpdatePosX sets the "pos_x" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsert) UpdatePosX() *SystemAnalysisEntityUpsert {
	u.SetExcluded(systemanalysisentity.FieldPosX)
	return u
}

// AddPosX adds v to the "pos_x" field.
func (u *SystemAnalysisEntityUpsert) AddPosX(v float64) *SystemAnalysisEntityUpsert {
	u.Add(systemanalysisentity.FieldPosX, v)
	return u
}

// ClearPosX clears the value of the "pos_x" field.
func (u *SystemAnalysisEntityUpsert) ClearPosX() *SystemAnalysisEntityUpsert {
	u.SetNull(systemanalysisentity.FieldPosX)
	return u
}

// SetPosY sets the "pos_y" field.
func (u *SystemAnalysisEntityUpsert) SetPosY(v float64) *SystemAnalysisEntityUpsert {
	u.Set(systemanalysisentity.FieldPosY, v)
	return u
}

// UpdatePosY sets the "pos_y" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsert) UpdatePosY() *SystemAnalysisEntityUpsert {
	u.SetExcluded(systemanalysisentity.FieldPosY)
	return u
}

// AddPosY adds v to the "pos_y" field.
func (u *SystemAnalysisEntityUpsert) AddPosY(v float64) *SystemAnalysisEntityUpsert {
	u.Add(systemanalysisentity.FieldPosY, v)
	return u
}

// ClearPosY clears the value of the "pos_y" field.
func (u *SystemAnalysisEntityUpsert) ClearPosY() *SystemAnalysisEntityUpsert {
	u.SetNull(systemanalysisentity.FieldPosY)
	return u
}

// SetHidden sets the "hidden" field.
func (u *SystemAnalysisEntityUpsert) SetHidden(v bool) *SystemAnalysisEntityUpsert {
	u.Set(systemanalysisentity.FieldHidden, v)
	return u
}

// UpdateHidden sets the "hidden" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsert) UpdateHidden() *SystemAnalysisEntityUpsert {
	u.SetExcluded(systemanalysisentity.FieldHidden)
	return u
}

// SetLabelOverride sets the "label_override" field.
func (u *SystemAnalysisEntityUpsert) SetLabelOverride(v string) *SystemAnalysisEntityUpsert {
	u.Set(systemanalysisentity.FieldLabelOverride, v)
	return u
}

// UpdateLabelOverride sets the "label_override" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsert) UpdateLabelOverride() *SystemAnalysisEntityUpsert {
	u.SetExcluded(systemanalysisentity.FieldLabelOverride)
	return u
}

// ClearLabelOverride clears the value of the "label_override" field.
func (u *SystemAnalysisEntityUpsert) ClearLabelOverride() *SystemAnalysisEntityUpsert {
	u.SetNull(systemanalysisentity.FieldLabelOverride)
	return u
}

// SetDescriptionOverride sets the "description_override" field.
func (u *SystemAnalysisEntityUpsert) SetDescriptionOverride(v string) *SystemAnalysisEntityUpsert {
	u.Set(systemanalysisentity.FieldDescriptionOverride, v)
	return u
}

// UpdateDescriptionOverride sets the "description_override" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsert) UpdateDescriptionOverride() *SystemAnalysisEntityUpsert {
	u.SetExcluded(systemanalysisentity.FieldDescriptionOverride)
	return u
}

// ClearDescriptionOverride clears the value of the "description_override" field.
func (u *SystemAnalysisEntityUpsert) ClearDescriptionOverride() *SystemAnalysisEntityUpsert {
	u.SetNull(systemanalysisentity.FieldDescriptionOverride)
	return u
}

// SetProperties sets the "properties" field.
func (u *SystemAnalysisEntityUpsert) SetProperties(v map[string]interface{}) *SystemAnalysisEntityUpsert {
	u.Set(systemanalysisentity.FieldProperties, v)
	return u
}

// UpdateProperties sets the "properties" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsert) UpdateProperties() *SystemAnalysisEntityUpsert {
	u.SetExcluded(systemanalysisentity.FieldProperties)
	return u
}

// ClearProperties clears the value of the "properties" field.
func (u *SystemAnalysisEntityUpsert) ClearProperties() *SystemAnalysisEntityUpsert {
	u.SetNull(systemanalysisentity.FieldProperties)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SystemAnalysisEntity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(systemanalysisentity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SystemAnalysisEntityUpsertOne) UpdateNewValues() *SystemAnalysisEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(systemanalysisentity.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(systemanalysisentity.FieldTenantID)
		}
		if _, exists := u.create.mutation.AnalysisID(); exists {
			s.SetIgnore(systemanalysisentity.FieldAnalysisID)
		}
		if _, exists := u.create.mutation.KnowledgeEntityID(); exists {
			s.SetIgnore(systemanalysisentity.FieldKnowledgeEntityID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SystemAnalysisEntity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SystemAnalysisEntityUpsertOne) Ignore() *SystemAnalysisEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemAnalysisEntityUpsertOne) DoNothing() *SystemAnalysisEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemAnalysisEntityCreate.OnConflict
// documentation for more info.
func (u *SystemAnalysisEntityUpsertOne) Update(set func(*SystemAnalysisEntityUpsert)) *SystemAnalysisEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemAnalysisEntityUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SystemAnalysisEntityUpsertOne) SetCreatedAt(v time.Time) *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertOne) UpdateCreatedAt() *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemAnalysisEntityUpsertOne) SetUpdatedAt(v time.Time) *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertOne) UpdateUpdatedAt() *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPosX sets the "pos_x" field.
func (u *SystemAnalysisEntityUpsertOne) SetPosX(v float64) *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetPosX(v)
	})
}

// AddPosX adds v to the "pos_x" field.
func (u *SystemAnalysisEntityUpsertOne) AddPosX(v float64) *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.AddPosX(v)
	})
}

// UpdatePosX sets the "pos_x" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertOne) UpdatePosX() *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdatePosX()
	})
}

// ClearPosX clears the value of the "pos_x" field.
func (u *SystemAnalysisEntityUpsertOne) ClearPosX() *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.ClearPosX()
	})
}

// SetPosY sets the "pos_y" field.
func (u *SystemAnalysisEntityUpsertOne) SetPosY(v float64) *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetPosY(v)
	})
}

// AddPosY adds v to the "pos_y" field.
func (u *SystemAnalysisEntityUpsertOne) AddPosY(v float64) *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.AddPosY(v)
	})
}

// UpdatePosY sets the "pos_y" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertOne) UpdatePosY() *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdatePosY()
	})
}

// ClearPosY clears the value of the "pos_y" field.
func (u *SystemAnalysisEntityUpsertOne) ClearPosY() *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.ClearPosY()
	})
}

// SetHidden sets the "hidden" field.
func (u *SystemAnalysisEntityUpsertOne) SetHidden(v bool) *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetHidden(v)
	})
}

// UpdateHidden sets the "hidden" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertOne) UpdateHidden() *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdateHidden()
	})
}

// SetLabelOverride sets the "label_override" field.
func (u *SystemAnalysisEntityUpsertOne) SetLabelOverride(v string) *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetLabelOverride(v)
	})
}

// UpdateLabelOverride sets the "label_override" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertOne) UpdateLabelOverride() *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdateLabelOverride()
	})
}

// ClearLabelOverride clears the value of the "label_override" field.
func (u *SystemAnalysisEntityUpsertOne) ClearLabelOverride() *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.ClearLabelOverride()
	})
}

// SetDescriptionOverride sets the "description_override" field.
func (u *SystemAnalysisEntityUpsertOne) SetDescriptionOverride(v string) *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetDescriptionOverride(v)
	})
}

// UpdateDescriptionOverride sets the "description_override" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertOne) UpdateDescriptionOverride() *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdateDescriptionOverride()
	})
}

// ClearDescriptionOverride clears the value of the "description_override" field.
func (u *SystemAnalysisEntityUpsertOne) ClearDescriptionOverride() *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.ClearDescriptionOverride()
	})
}

// SetProperties sets the "properties" field.
func (u *SystemAnalysisEntityUpsertOne) SetProperties(v map[string]interface{}) *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetProperties(v)
	})
}

// UpdateProperties sets the "properties" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertOne) UpdateProperties() *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdateProperties()
	})
}

// ClearProperties clears the value of the "properties" field.
func (u *SystemAnalysisEntityUpsertOne) ClearProperties() *SystemAnalysisEntityUpsertOne {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.ClearProperties()
	})
}

// Exec executes the query.
func (u *SystemAnalysisEntityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemAnalysisEntityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemAnalysisEntityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SystemAnalysisEntityUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SystemAnalysisEntityUpsertOne.ID is not supported by MySQL driver. Use SystemAnalysisEntityUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SystemAnalysisEntityUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SystemAnalysisEntityCreateBulk is the builder for creating many SystemAnalysisEntity entities in bulk.
type SystemAnalysisEntityCreateBulk struct {
	config
	err      error
	builders []*SystemAnalysisEntityCreate
	conflict []sql.ConflictOption
}

// Save creates the SystemAnalysisEntity entities in the database.
func (_c *SystemAnalysisEntityCreateBulk) Save(ctx context.Context) ([]*SystemAnalysisEntity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SystemAnalysisEntity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SystemAnalysisEntityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SystemAnalysisEntityCreateBulk) SaveX(ctx context.Context) []*SystemAnalysisEntity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemAnalysisEntityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemAnalysisEntityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SystemAnalysisEntity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemAnalysisEntityUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemAnalysisEntityCreateBulk) OnConflict(opts ...sql.ConflictOption) *SystemAnalysisEntityUpsertBulk {
	_c.conflict = opts
	return &SystemAnalysisEntityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SystemAnalysisEntity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemAnalysisEntityCreateBulk) OnConflictColumns(columns ...string) *SystemAnalysisEntityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemAnalysisEntityUpsertBulk{
		create: _c,
	}
}

// SystemAnalysisEntityUpsertBulk is the builder for "upsert"-ing
// a bulk of SystemAnalysisEntity nodes.
type SystemAnalysisEntityUpsertBulk struct {
	create *SystemAnalysisEntityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SystemAnalysisEntity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(systemanalysisentity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SystemAnalysisEntityUpsertBulk) UpdateNewValues() *SystemAnalysisEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(systemanalysisentity.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(systemanalysisentity.FieldTenantID)
			}
			if _, exists := b.mutation.AnalysisID(); exists {
				s.SetIgnore(systemanalysisentity.FieldAnalysisID)
			}
			if _, exists := b.mutation.KnowledgeEntityID(); exists {
				s.SetIgnore(systemanalysisentity.FieldKnowledgeEntityID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SystemAnalysisEntity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SystemAnalysisEntityUpsertBulk) Ignore() *SystemAnalysisEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemAnalysisEntityUpsertBulk) DoNothing() *SystemAnalysisEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemAnalysisEntityCreateBulk.OnConflict
// documentation for more info.
func (u *SystemAnalysisEntityUpsertBulk) Update(set func(*SystemAnalysisEntityUpsert)) *SystemAnalysisEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemAnalysisEntityUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SystemAnalysisEntityUpsertBulk) SetCreatedAt(v time.Time) *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertBulk) UpdateCreatedAt() *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemAnalysisEntityUpsertBulk) SetUpdatedAt(v time.Time) *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertBulk) UpdateUpdatedAt() *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPosX sets the "pos_x" field.
func (u *SystemAnalysisEntityUpsertBulk) SetPosX(v float64) *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetPosX(v)
	})
}

// AddPosX adds v to the "pos_x" field.
func (u *SystemAnalysisEntityUpsertBulk) AddPosX(v float64) *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.AddPosX(v)
	})
}

// UpdatePosX sets the "pos_x" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertBulk) UpdatePosX() *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdatePosX()
	})
}

// ClearPosX clears the value of the "pos_x" field.
func (u *SystemAnalysisEntityUpsertBulk) ClearPosX() *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.ClearPosX()
	})
}

// SetPosY sets the "pos_y" field.
func (u *SystemAnalysisEntityUpsertBulk) SetPosY(v float64) *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetPosY(v)
	})
}

// AddPosY adds v to the "pos_y" field.
func (u *SystemAnalysisEntityUpsertBulk) AddPosY(v float64) *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.AddPosY(v)
	})
}

// UpdatePosY sets the "pos_y" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertBulk) UpdatePosY() *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdatePosY()
	})
}

// ClearPosY clears the value of the "pos_y" field.
func (u *SystemAnalysisEntityUpsertBulk) ClearPosY() *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.ClearPosY()
	})
}

// SetHidden sets the "hidden" field.
func (u *SystemAnalysisEntityUpsertBulk) SetHidden(v bool) *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetHidden(v)
	})
}

// UpdateHidden sets the "hidden" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertBulk) UpdateHidden() *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdateHidden()
	})
}

// SetLabelOverride sets the "label_override" field.
func (u *SystemAnalysisEntityUpsertBulk) SetLabelOverride(v string) *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetLabelOverride(v)
	})
}

// UpdateLabelOverride sets the "label_override" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertBulk) UpdateLabelOverride() *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdateLabelOverride()
	})
}

// ClearLabelOverride clears the value of the "label_override" field.
func (u *SystemAnalysisEntityUpsertBulk) ClearLabelOverride() *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.ClearLabelOverride()
	})
}

// SetDescriptionOverride sets the "description_override" field.
func (u *SystemAnalysisEntityUpsertBulk) SetDescriptionOverride(v string) *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetDescriptionOverride(v)
	})
}

// UpdateDescriptionOverride sets the "description_override" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertBulk) UpdateDescriptionOverride() *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdateDescriptionOverride()
	})
}

// ClearDescriptionOverride clears the value of the "description_override" field.
func (u *SystemAnalysisEntityUpsertBulk) ClearDescriptionOverride() *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.ClearDescriptionOverride()
	})
}

// SetProperties sets the "properties" field.
func (u *SystemAnalysisEntityUpsertBulk) SetProperties(v map[string]interface{}) *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.SetProperties(v)
	})
}

// UpdateProperties sets the "properties" field to the value that was provided on create.
func (u *SystemAnalysisEntityUpsertBulk) UpdateProperties() *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.UpdateProperties()
	})
}

// ClearProperties clears the value of the "properties" field.
func (u *SystemAnalysisEntityUpsertBulk) ClearProperties() *SystemAnalysisEntityUpsertBulk {
	return u.Update(func(s *SystemAnalysisEntityUpsert) {
		s.ClearProperties()
	})
}

// Exec executes the query.
func (u *SystemAnalysisEntityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SystemAnalysisEntityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemAnalysisEntityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemAnalysisEntityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
