name: "rezible"

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports: ["5432:5432"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rezible
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "postgres"]
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 1s
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "./devenv/postgres/:/docker-entrypoint-initdb.d/"

  dex:
    scale: 1
    image: dexidp/dex:v2.41.1
    restart: on-failure:2
    ports: ["${AUTH_PORT}:${AUTH_PORT}"]
    volumes:
      - "./devenv/dex-config.yaml:/etc/dex/config.yaml:ro"
      - "./devenv/localias-ca.crt:/etc/ssl/localias.crt:ro"
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    environment:
      - PORT=${AUTH_PORT}
      - AUTH_URL=${AUTH_URL}
      - APP_URL=${APP_URL}
      - API_URL=${API_URL}

  telemetry:
    profiles: ["telemetry"]
    image: grafana/otel-lgtm:latest
    container_name: otel-lgtm
    ports:
      - "3000"   # Grafana UI
      - "4317"   # OpenTelemetry gRPC collector
    environment:
      ENABLE_LOGS_ALL: "false"

  backend:
    profiles: ["apps"]
    restart: on-failure:1
    build:
      context: packages/apps/backend
      dockerfile: dev.Dockerfile
    working_dir: "/app"
    volumes:
      - "./packages/apps/backend/:/app/"
      - "./devenv/localias-ca.crt:/usr/local/share/ca-certificates/localias.crt:ro"
    ports: ["7001"]
    env_file: [".env", ".env.dev"]
    environment:
      - "POSTGRES__HOST=postgres"
      - "SERVER__HTTP__DOCUMENTS_PROXY__PROXY_HOST=http://documents-server:7002"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    profiles: ["apps"]
    restart: on-failure:1
    build:
      context: .
      dockerfile: packages/apps/frontend/dev.Dockerfile
    working_dir: "/app"
    volumes:
      - "./packages/:/app/packages/"
      - "./package.json:/app/package.json"
      - "./bun.lock:/app/bun.lock"
      - "./devenv/localias-ca.crt:/usr/local/share/ca-certificates/localias.crt:ro"
    environment:
      - "PORT=7000"
    ports: ["7000"]

#  rez-documents-server:
#    depends_on: [postgres]
#    build:
#      context: .
#      dockerfile: packages/apps/documents-server/Dockerfile
#    ports: ["7002"]
#    volumes: ["./scripts/certs/localias-ca.crt:/etc/ssl/localias.crt:ro"]
#    env_file: [".env.dev", ".env"]
