environment: [".env", ".env.workspace"]

processes:
  dex:
    command: just devenv run-dex
    availability:
      restart: on_failure
      max_restarts: 1

  backend:
    command: just backend dev
    environment:
      - AUTH__OIDC__ISSUER=${AUTH_URL}
      - SERVER__HTTP__PORT=${BACKEND_PORT}
    availability:
      restart: always

  frontend:
    command: bun run --filter=@rezible/frontend dev
    availability:
      restart: always

  documents-server:
    disabled: true
    command: bun run --filter=@rezible/documents-server dev
    availability:
      restart: on_failure
      max_restarts: 1
