version: "1.24"

# upgrade after resolved:
# https://github.com/F1bonacc1/process-compose/issues/258

processes:
  backend:
    command: just dev-backend
    availability:
      restart: always
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: 7001
        path: "/health"
      initial_delay_seconds: 3
    depends_on:
      documents-server:
        condition: process_started

  frontend:
    command: just run-frontend dev
    availability:
      restart: on_failure
      max_restarts: 1
    depends_on:
      backend:
        condition: process_started

  documents-server:
    command: just run-documents-server dev
    availability:
      restart: on_failure
      max_restarts: 1
