// Code generated by ent, DO NOT EDIT.

package knowledgeentity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/rezible/rezible/ent/internal"
	"github.com/rezible/rezible/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldEQ(FieldUpdatedAt, v))
}

// Subkind applies equality check predicate on the "subkind" field. It's identical to SubkindEQ.
func Subkind(v string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldEQ(FieldSubkind, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldNotIn(FieldTenantID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldLTE(FieldUpdatedAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldNotIn(FieldKind, vs...))
}

// SubkindEQ applies the EQ predicate on the "subkind" field.
func SubkindEQ(v string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldEQ(FieldSubkind, v))
}

// SubkindNEQ applies the NEQ predicate on the "subkind" field.
func SubkindNEQ(v string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldNEQ(FieldSubkind, v))
}

// SubkindIn applies the In predicate on the "subkind" field.
func SubkindIn(vs ...string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldIn(FieldSubkind, vs...))
}

// SubkindNotIn applies the NotIn predicate on the "subkind" field.
func SubkindNotIn(vs ...string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldNotIn(FieldSubkind, vs...))
}

// SubkindGT applies the GT predicate on the "subkind" field.
func SubkindGT(v string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldGT(FieldSubkind, v))
}

// SubkindGTE applies the GTE predicate on the "subkind" field.
func SubkindGTE(v string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldGTE(FieldSubkind, v))
}

// SubkindLT applies the LT predicate on the "subkind" field.
func SubkindLT(v string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldLT(FieldSubkind, v))
}

// SubkindLTE applies the LTE predicate on the "subkind" field.
func SubkindLTE(v string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldLTE(FieldSubkind, v))
}

// SubkindContains applies the Contains predicate on the "subkind" field.
func SubkindContains(v string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldContains(FieldSubkind, v))
}

// SubkindHasPrefix applies the HasPrefix predicate on the "subkind" field.
func SubkindHasPrefix(v string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldHasPrefix(FieldSubkind, v))
}

// SubkindHasSuffix applies the HasSuffix predicate on the "subkind" field.
func SubkindHasSuffix(v string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldHasSuffix(FieldSubkind, v))
}

// SubkindEqualFold applies the EqualFold predicate on the "subkind" field.
func SubkindEqualFold(v string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldEqualFold(FieldSubkind, v))
}

// SubkindContainsFold applies the ContainsFold predicate on the "subkind" field.
func SubkindContainsFold(v string) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.FieldContainsFold(FieldSubkind, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Tenant
		step.Edge.Schema = schemaConfig.KnowledgeEntity
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(func(s *sql.Selector) {
		step := newTenantStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Tenant
		step.Edge.Schema = schemaConfig.KnowledgeEntity
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAliases applies the HasEdge predicate on the "aliases" edge.
func HasAliases() predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, AliasesTable, AliasesColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeSubjectAlias
		step.Edge.Schema = schemaConfig.KnowledgeSubjectAlias
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAliasesWith applies the HasEdge predicate on the "aliases" edge with a given conditions (other predicates).
func HasAliasesWith(preds ...predicate.KnowledgeSubjectAlias) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(func(s *sql.Selector) {
		step := newAliasesStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeSubjectAlias
		step.Edge.Schema = schemaConfig.KnowledgeSubjectAlias
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSourceRelationships applies the HasEdge predicate on the "source_relationships" edge.
func HasSourceRelationships() predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, SourceRelationshipsTable, SourceRelationshipsColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeRelationship
		step.Edge.Schema = schemaConfig.KnowledgeRelationship
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceRelationshipsWith applies the HasEdge predicate on the "source_relationships" edge with a given conditions (other predicates).
func HasSourceRelationshipsWith(preds ...predicate.KnowledgeRelationship) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(func(s *sql.Selector) {
		step := newSourceRelationshipsStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeRelationship
		step.Edge.Schema = schemaConfig.KnowledgeRelationship
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTargetRelationships applies the HasEdge predicate on the "target_relationships" edge.
func HasTargetRelationships() predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TargetRelationshipsTable, TargetRelationshipsColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeRelationship
		step.Edge.Schema = schemaConfig.KnowledgeRelationship
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetRelationshipsWith applies the HasEdge predicate on the "target_relationships" edge with a given conditions (other predicates).
func HasTargetRelationshipsWith(preds ...predicate.KnowledgeRelationship) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(func(s *sql.Selector) {
		step := newTargetRelationshipsStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeRelationship
		step.Edge.Schema = schemaConfig.KnowledgeRelationship
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KnowledgeEntity) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KnowledgeEntity) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KnowledgeEntity) predicate.KnowledgeEntity {
	return predicate.KnowledgeEntity(sql.NotPredicates(p))
}
