with-expecter: true
issue-845-fix: true
resolve-type-alias: false
disable-version-string: true

packages:
  github.com/rezible/rezible:
    config:
      dir: internal/testkit/mocks
      outpkg: mocks
      filename: "{{ .InterfaceName }}.go"
    interfaces:
      JobsService: {}
      MessageService: {}
      UserService: {}
      OrganizationService: {}
