issuer: "{{ .Env.ISSUER }}"
web:
  http: "0.0.0.0:7011"
  allowedOrigins: ["{{ .Env.APP_URL }}", "{{ .Env.API_URL }}"]
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
oauth2:
  responseTypes: ["code"]
  skipApprovalScreen: true
  alwaysShowLoginScreen: false
staticClients:
  - id: test-client
    secret: superdupersecret
    name: "Web App"
    redirectURIs: ["{{ .Env.APP_URL }}/api/auth/callback"]
enablePasswordDB: true
staticPasswords:
  # password: $()
  - email: "admin@dev.rezible.com"
    username: "admin"
    userID: "cd8cc83f-de81-4f05-a64d-5e4105a35142"
    hash: "$2y$10$gAIxkHz02W.P1QqNhB6LCeGO8KsCCWwAU7odIGeR0TPmBuq8wVnom"
  - email: "user@dev.rezible.com"
    username: "user"
    userID: "00cb6dd1-6be0-4b2a-83ad-4f16468f9055"
    hash: "$2y$10$gAIxkHz02W.P1QqNhB6LCeGO8KsCCWwAU7odIGeR0TPmBuq8wVnom"
