// Code generated by ent, DO NOT EDIT.

package knowledgefacthistory

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the knowledgefacthistory type in the database.
	Label = "knowledge_fact_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldFactKind holds the string denoting the fact_kind field in the database.
	FieldFactKind = "fact_kind"
	// FieldAliasID holds the string denoting the alias_id field in the database.
	FieldAliasID = "alias_id"
	// FieldRelationshipID holds the string denoting the relationship_id field in the database.
	FieldRelationshipID = "relationship_id"
	// FieldNormalizedEventID holds the string denoting the normalized_event_id field in the database.
	FieldNormalizedEventID = "normalized_event_id"
	// FieldEventKind holds the string denoting the event_kind field in the database.
	FieldEventKind = "event_kind"
	// FieldHistoryKey holds the string denoting the history_key field in the database.
	FieldHistoryKey = "history_key"
	// FieldOccurredAt holds the string denoting the occurred_at field in the database.
	FieldOccurredAt = "occurred_at"
	// FieldRecordedAt holds the string denoting the recorded_at field in the database.
	FieldRecordedAt = "recorded_at"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldProviderSource holds the string denoting the provider_source field in the database.
	FieldProviderSource = "provider_source"
	// FieldProviderEventRef holds the string denoting the provider_event_ref field in the database.
	FieldProviderEventRef = "provider_event_ref"
	// FieldExtractionMethod holds the string denoting the extraction_method field in the database.
	FieldExtractionMethod = "extraction_method"
	// FieldAttributes holds the string denoting the attributes field in the database.
	FieldAttributes = "attributes"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeAlias holds the string denoting the alias edge name in mutations.
	EdgeAlias = "alias"
	// EdgeRelationship holds the string denoting the relationship edge name in mutations.
	EdgeRelationship = "relationship"
	// EdgeNormalizedEvent holds the string denoting the normalized_event edge name in mutations.
	EdgeNormalizedEvent = "normalized_event"
	// Table holds the table name of the knowledgefacthistory in the database.
	Table = "knowledge_fact_histories"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "knowledge_fact_histories"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// AliasTable is the table that holds the alias relation/edge.
	AliasTable = "knowledge_fact_histories"
	// AliasInverseTable is the table name for the KnowledgeEntityAlias entity.
	// It exists in this package in order to avoid circular dependency with the "knowledgeentityalias" package.
	AliasInverseTable = "knowledge_entity_alias"
	// AliasColumn is the table column denoting the alias relation/edge.
	AliasColumn = "alias_id"
	// RelationshipTable is the table that holds the relationship relation/edge.
	RelationshipTable = "knowledge_fact_histories"
	// RelationshipInverseTable is the table name for the KnowledgeRelationship entity.
	// It exists in this package in order to avoid circular dependency with the "knowledgerelationship" package.
	RelationshipInverseTable = "knowledge_relationships"
	// RelationshipColumn is the table column denoting the relationship relation/edge.
	RelationshipColumn = "relationship_id"
	// NormalizedEventTable is the table that holds the normalized_event relation/edge.
	NormalizedEventTable = "knowledge_fact_histories"
	// NormalizedEventInverseTable is the table name for the NormalizedEvent entity.
	// It exists in this package in order to avoid circular dependency with the "normalizedevent" package.
	NormalizedEventInverseTable = "normalized_events"
	// NormalizedEventColumn is the table column denoting the normalized_event relation/edge.
	NormalizedEventColumn = "normalized_event_id"
)

// Columns holds all SQL columns for knowledgefacthistory fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldFactKind,
	FieldAliasID,
	FieldRelationshipID,
	FieldNormalizedEventID,
	FieldEventKind,
	FieldHistoryKey,
	FieldOccurredAt,
	FieldRecordedAt,
	FieldProvider,
	FieldProviderSource,
	FieldProviderEventRef,
	FieldExtractionMethod,
	FieldAttributes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/rezible/rezible/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// EventKindValidator is a validator for the "event_kind" field. It is called by the builders before save.
	EventKindValidator func(string) error
	// HistoryKeyValidator is a validator for the "history_key" field. It is called by the builders before save.
	HistoryKeyValidator func(string) error
	// DefaultRecordedAt holds the default value on creation for the "recorded_at" field.
	DefaultRecordedAt func() time.Time
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// ProviderSourceValidator is a validator for the "provider_source" field. It is called by the builders before save.
	ProviderSourceValidator func(string) error
	// ProviderEventRefValidator is a validator for the "provider_event_ref" field. It is called by the builders before save.
	ProviderEventRefValidator func(string) error
	// ExtractionMethodValidator is a validator for the "extraction_method" field. It is called by the builders before save.
	ExtractionMethodValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// FactKind defines the type for the "fact_kind" enum field.
type FactKind string

// FactKind values.
const (
	FactKindAlias        FactKind = "alias"
	FactKindRelationship FactKind = "relationship"
)

func (fk FactKind) String() string {
	return string(fk)
}

// FactKindValidator is a validator for the "fact_kind" field enum values. It is called by the builders before save.
func FactKindValidator(fk FactKind) error {
	switch fk {
	case FactKindAlias, FactKindRelationship:
		return nil
	default:
		return fmt.Errorf("knowledgefacthistory: invalid enum value for fact_kind field: %q", fk)
	}
}

// OrderOption defines the ordering options for the KnowledgeFactHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByFactKind orders the results by the fact_kind field.
func ByFactKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFactKind, opts...).ToFunc()
}

// ByAliasID orders the results by the alias_id field.
func ByAliasID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAliasID, opts...).ToFunc()
}

// ByRelationshipID orders the results by the relationship_id field.
func ByRelationshipID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelationshipID, opts...).ToFunc()
}

// ByNormalizedEventID orders the results by the normalized_event_id field.
func ByNormalizedEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNormalizedEventID, opts...).ToFunc()
}

// ByEventKind orders the results by the event_kind field.
func ByEventKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventKind, opts...).ToFunc()
}

// ByHistoryKey orders the results by the history_key field.
func ByHistoryKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHistoryKey, opts...).ToFunc()
}

// ByOccurredAt orders the results by the occurred_at field.
func ByOccurredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOccurredAt, opts...).ToFunc()
}

// ByRecordedAt orders the results by the recorded_at field.
func ByRecordedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordedAt, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByProviderSource orders the results by the provider_source field.
func ByProviderSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderSource, opts...).ToFunc()
}

// ByProviderEventRef orders the results by the provider_event_ref field.
func ByProviderEventRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderEventRef, opts...).ToFunc()
}

// ByExtractionMethod orders the results by the extraction_method field.
func ByExtractionMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtractionMethod, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByAliasField orders the results by alias field.
func ByAliasField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAliasStep(), sql.OrderByField(field, opts...))
	}
}

// ByRelationshipField orders the results by relationship field.
func ByRelationshipField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRelationshipStep(), sql.OrderByField(field, opts...))
	}
}

// ByNormalizedEventField orders the results by normalized_event field.
func ByNormalizedEventField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNormalizedEventStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
	)
}
func newAliasStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AliasInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AliasTable, AliasColumn),
	)
}
func newRelationshipStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RelationshipInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RelationshipTable, RelationshipColumn),
	)
}
func newNormalizedEventStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NormalizedEventInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, NormalizedEventTable, NormalizedEventColumn),
	)
}
