// Code generated by ent, DO NOT EDIT.

package knowledgefacthistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/rezible/rezible/ent/internal"
	"github.com/rezible/rezible/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldTenantID, v))
}

// FactKind applies equality check predicate on the "fact_kind" field. It's identical to FactKindEQ.
func FactKind(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldFactKind, v))
}

// AliasID applies equality check predicate on the "alias_id" field. It's identical to AliasIDEQ.
func AliasID(v uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldAliasID, v))
}

// RelationshipID applies equality check predicate on the "relationship_id" field. It's identical to RelationshipIDEQ.
func RelationshipID(v uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldRelationshipID, v))
}

// NormalizedEventID applies equality check predicate on the "normalized_event_id" field. It's identical to NormalizedEventIDEQ.
func NormalizedEventID(v uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldNormalizedEventID, v))
}

// EventKind applies equality check predicate on the "event_kind" field. It's identical to EventKindEQ.
func EventKind(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldEventKind, v))
}

// HistoryKey applies equality check predicate on the "history_key" field. It's identical to HistoryKeyEQ.
func HistoryKey(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldHistoryKey, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldOccurredAt, v))
}

// RecordedAt applies equality check predicate on the "recorded_at" field. It's identical to RecordedAtEQ.
func RecordedAt(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldRecordedAt, v))
}

// SourceProvider applies equality check predicate on the "source_provider" field. It's identical to SourceProviderEQ.
func SourceProvider(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldSourceProvider, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldSource, v))
}

// SourceRef applies equality check predicate on the "source_ref" field. It's identical to SourceRefEQ.
func SourceRef(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldSourceRef, v))
}

// ExtractionMethod applies equality check predicate on the "extraction_method" field. It's identical to ExtractionMethodEQ.
func ExtractionMethod(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldExtractionMethod, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldTenantID, vs...))
}

// FactKindEQ applies the EQ predicate on the "fact_kind" field.
func FactKindEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldFactKind, v))
}

// FactKindNEQ applies the NEQ predicate on the "fact_kind" field.
func FactKindNEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldFactKind, v))
}

// FactKindIn applies the In predicate on the "fact_kind" field.
func FactKindIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldFactKind, vs...))
}

// FactKindNotIn applies the NotIn predicate on the "fact_kind" field.
func FactKindNotIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldFactKind, vs...))
}

// FactKindGT applies the GT predicate on the "fact_kind" field.
func FactKindGT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGT(FieldFactKind, v))
}

// FactKindGTE applies the GTE predicate on the "fact_kind" field.
func FactKindGTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGTE(FieldFactKind, v))
}

// FactKindLT applies the LT predicate on the "fact_kind" field.
func FactKindLT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLT(FieldFactKind, v))
}

// FactKindLTE applies the LTE predicate on the "fact_kind" field.
func FactKindLTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLTE(FieldFactKind, v))
}

// FactKindContains applies the Contains predicate on the "fact_kind" field.
func FactKindContains(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContains(FieldFactKind, v))
}

// FactKindHasPrefix applies the HasPrefix predicate on the "fact_kind" field.
func FactKindHasPrefix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasPrefix(FieldFactKind, v))
}

// FactKindHasSuffix applies the HasSuffix predicate on the "fact_kind" field.
func FactKindHasSuffix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasSuffix(FieldFactKind, v))
}

// FactKindEqualFold applies the EqualFold predicate on the "fact_kind" field.
func FactKindEqualFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEqualFold(FieldFactKind, v))
}

// FactKindContainsFold applies the ContainsFold predicate on the "fact_kind" field.
func FactKindContainsFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContainsFold(FieldFactKind, v))
}

// AliasIDEQ applies the EQ predicate on the "alias_id" field.
func AliasIDEQ(v uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldAliasID, v))
}

// AliasIDNEQ applies the NEQ predicate on the "alias_id" field.
func AliasIDNEQ(v uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldAliasID, v))
}

// AliasIDIn applies the In predicate on the "alias_id" field.
func AliasIDIn(vs ...uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldAliasID, vs...))
}

// AliasIDNotIn applies the NotIn predicate on the "alias_id" field.
func AliasIDNotIn(vs ...uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldAliasID, vs...))
}

// AliasIDIsNil applies the IsNil predicate on the "alias_id" field.
func AliasIDIsNil() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIsNull(FieldAliasID))
}

// AliasIDNotNil applies the NotNil predicate on the "alias_id" field.
func AliasIDNotNil() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotNull(FieldAliasID))
}

// RelationshipIDEQ applies the EQ predicate on the "relationship_id" field.
func RelationshipIDEQ(v uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldRelationshipID, v))
}

// RelationshipIDNEQ applies the NEQ predicate on the "relationship_id" field.
func RelationshipIDNEQ(v uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldRelationshipID, v))
}

// RelationshipIDIn applies the In predicate on the "relationship_id" field.
func RelationshipIDIn(vs ...uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldRelationshipID, vs...))
}

// RelationshipIDNotIn applies the NotIn predicate on the "relationship_id" field.
func RelationshipIDNotIn(vs ...uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldRelationshipID, vs...))
}

// RelationshipIDIsNil applies the IsNil predicate on the "relationship_id" field.
func RelationshipIDIsNil() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIsNull(FieldRelationshipID))
}

// RelationshipIDNotNil applies the NotNil predicate on the "relationship_id" field.
func RelationshipIDNotNil() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotNull(FieldRelationshipID))
}

// NormalizedEventIDEQ applies the EQ predicate on the "normalized_event_id" field.
func NormalizedEventIDEQ(v uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldNormalizedEventID, v))
}

// NormalizedEventIDNEQ applies the NEQ predicate on the "normalized_event_id" field.
func NormalizedEventIDNEQ(v uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldNormalizedEventID, v))
}

// NormalizedEventIDIn applies the In predicate on the "normalized_event_id" field.
func NormalizedEventIDIn(vs ...uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldNormalizedEventID, vs...))
}

// NormalizedEventIDNotIn applies the NotIn predicate on the "normalized_event_id" field.
func NormalizedEventIDNotIn(vs ...uuid.UUID) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldNormalizedEventID, vs...))
}

// NormalizedEventIDIsNil applies the IsNil predicate on the "normalized_event_id" field.
func NormalizedEventIDIsNil() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIsNull(FieldNormalizedEventID))
}

// NormalizedEventIDNotNil applies the NotNil predicate on the "normalized_event_id" field.
func NormalizedEventIDNotNil() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotNull(FieldNormalizedEventID))
}

// EventKindEQ applies the EQ predicate on the "event_kind" field.
func EventKindEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldEventKind, v))
}

// EventKindNEQ applies the NEQ predicate on the "event_kind" field.
func EventKindNEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldEventKind, v))
}

// EventKindIn applies the In predicate on the "event_kind" field.
func EventKindIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldEventKind, vs...))
}

// EventKindNotIn applies the NotIn predicate on the "event_kind" field.
func EventKindNotIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldEventKind, vs...))
}

// EventKindGT applies the GT predicate on the "event_kind" field.
func EventKindGT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGT(FieldEventKind, v))
}

// EventKindGTE applies the GTE predicate on the "event_kind" field.
func EventKindGTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGTE(FieldEventKind, v))
}

// EventKindLT applies the LT predicate on the "event_kind" field.
func EventKindLT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLT(FieldEventKind, v))
}

// EventKindLTE applies the LTE predicate on the "event_kind" field.
func EventKindLTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLTE(FieldEventKind, v))
}

// EventKindContains applies the Contains predicate on the "event_kind" field.
func EventKindContains(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContains(FieldEventKind, v))
}

// EventKindHasPrefix applies the HasPrefix predicate on the "event_kind" field.
func EventKindHasPrefix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasPrefix(FieldEventKind, v))
}

// EventKindHasSuffix applies the HasSuffix predicate on the "event_kind" field.
func EventKindHasSuffix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasSuffix(FieldEventKind, v))
}

// EventKindEqualFold applies the EqualFold predicate on the "event_kind" field.
func EventKindEqualFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEqualFold(FieldEventKind, v))
}

// EventKindContainsFold applies the ContainsFold predicate on the "event_kind" field.
func EventKindContainsFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContainsFold(FieldEventKind, v))
}

// HistoryKeyEQ applies the EQ predicate on the "history_key" field.
func HistoryKeyEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldHistoryKey, v))
}

// HistoryKeyNEQ applies the NEQ predicate on the "history_key" field.
func HistoryKeyNEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldHistoryKey, v))
}

// HistoryKeyIn applies the In predicate on the "history_key" field.
func HistoryKeyIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldHistoryKey, vs...))
}

// HistoryKeyNotIn applies the NotIn predicate on the "history_key" field.
func HistoryKeyNotIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldHistoryKey, vs...))
}

// HistoryKeyGT applies the GT predicate on the "history_key" field.
func HistoryKeyGT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGT(FieldHistoryKey, v))
}

// HistoryKeyGTE applies the GTE predicate on the "history_key" field.
func HistoryKeyGTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGTE(FieldHistoryKey, v))
}

// HistoryKeyLT applies the LT predicate on the "history_key" field.
func HistoryKeyLT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLT(FieldHistoryKey, v))
}

// HistoryKeyLTE applies the LTE predicate on the "history_key" field.
func HistoryKeyLTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLTE(FieldHistoryKey, v))
}

// HistoryKeyContains applies the Contains predicate on the "history_key" field.
func HistoryKeyContains(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContains(FieldHistoryKey, v))
}

// HistoryKeyHasPrefix applies the HasPrefix predicate on the "history_key" field.
func HistoryKeyHasPrefix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasPrefix(FieldHistoryKey, v))
}

// HistoryKeyHasSuffix applies the HasSuffix predicate on the "history_key" field.
func HistoryKeyHasSuffix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasSuffix(FieldHistoryKey, v))
}

// HistoryKeyEqualFold applies the EqualFold predicate on the "history_key" field.
func HistoryKeyEqualFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEqualFold(FieldHistoryKey, v))
}

// HistoryKeyContainsFold applies the ContainsFold predicate on the "history_key" field.
func HistoryKeyContainsFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContainsFold(FieldHistoryKey, v))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLTE(FieldOccurredAt, v))
}

// RecordedAtEQ applies the EQ predicate on the "recorded_at" field.
func RecordedAtEQ(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldRecordedAt, v))
}

// RecordedAtNEQ applies the NEQ predicate on the "recorded_at" field.
func RecordedAtNEQ(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldRecordedAt, v))
}

// RecordedAtIn applies the In predicate on the "recorded_at" field.
func RecordedAtIn(vs ...time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldRecordedAt, vs...))
}

// RecordedAtNotIn applies the NotIn predicate on the "recorded_at" field.
func RecordedAtNotIn(vs ...time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldRecordedAt, vs...))
}

// RecordedAtGT applies the GT predicate on the "recorded_at" field.
func RecordedAtGT(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGT(FieldRecordedAt, v))
}

// RecordedAtGTE applies the GTE predicate on the "recorded_at" field.
func RecordedAtGTE(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGTE(FieldRecordedAt, v))
}

// RecordedAtLT applies the LT predicate on the "recorded_at" field.
func RecordedAtLT(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLT(FieldRecordedAt, v))
}

// RecordedAtLTE applies the LTE predicate on the "recorded_at" field.
func RecordedAtLTE(v time.Time) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLTE(FieldRecordedAt, v))
}

// SourceProviderEQ applies the EQ predicate on the "source_provider" field.
func SourceProviderEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldSourceProvider, v))
}

// SourceProviderNEQ applies the NEQ predicate on the "source_provider" field.
func SourceProviderNEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldSourceProvider, v))
}

// SourceProviderIn applies the In predicate on the "source_provider" field.
func SourceProviderIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldSourceProvider, vs...))
}

// SourceProviderNotIn applies the NotIn predicate on the "source_provider" field.
func SourceProviderNotIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldSourceProvider, vs...))
}

// SourceProviderGT applies the GT predicate on the "source_provider" field.
func SourceProviderGT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGT(FieldSourceProvider, v))
}

// SourceProviderGTE applies the GTE predicate on the "source_provider" field.
func SourceProviderGTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGTE(FieldSourceProvider, v))
}

// SourceProviderLT applies the LT predicate on the "source_provider" field.
func SourceProviderLT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLT(FieldSourceProvider, v))
}

// SourceProviderLTE applies the LTE predicate on the "source_provider" field.
func SourceProviderLTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLTE(FieldSourceProvider, v))
}

// SourceProviderContains applies the Contains predicate on the "source_provider" field.
func SourceProviderContains(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContains(FieldSourceProvider, v))
}

// SourceProviderHasPrefix applies the HasPrefix predicate on the "source_provider" field.
func SourceProviderHasPrefix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasPrefix(FieldSourceProvider, v))
}

// SourceProviderHasSuffix applies the HasSuffix predicate on the "source_provider" field.
func SourceProviderHasSuffix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasSuffix(FieldSourceProvider, v))
}

// SourceProviderEqualFold applies the EqualFold predicate on the "source_provider" field.
func SourceProviderEqualFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEqualFold(FieldSourceProvider, v))
}

// SourceProviderContainsFold applies the ContainsFold predicate on the "source_provider" field.
func SourceProviderContainsFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContainsFold(FieldSourceProvider, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContainsFold(FieldSource, v))
}

// SourceRefEQ applies the EQ predicate on the "source_ref" field.
func SourceRefEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldSourceRef, v))
}

// SourceRefNEQ applies the NEQ predicate on the "source_ref" field.
func SourceRefNEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldSourceRef, v))
}

// SourceRefIn applies the In predicate on the "source_ref" field.
func SourceRefIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldSourceRef, vs...))
}

// SourceRefNotIn applies the NotIn predicate on the "source_ref" field.
func SourceRefNotIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldSourceRef, vs...))
}

// SourceRefGT applies the GT predicate on the "source_ref" field.
func SourceRefGT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGT(FieldSourceRef, v))
}

// SourceRefGTE applies the GTE predicate on the "source_ref" field.
func SourceRefGTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGTE(FieldSourceRef, v))
}

// SourceRefLT applies the LT predicate on the "source_ref" field.
func SourceRefLT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLT(FieldSourceRef, v))
}

// SourceRefLTE applies the LTE predicate on the "source_ref" field.
func SourceRefLTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLTE(FieldSourceRef, v))
}

// SourceRefContains applies the Contains predicate on the "source_ref" field.
func SourceRefContains(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContains(FieldSourceRef, v))
}

// SourceRefHasPrefix applies the HasPrefix predicate on the "source_ref" field.
func SourceRefHasPrefix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasPrefix(FieldSourceRef, v))
}

// SourceRefHasSuffix applies the HasSuffix predicate on the "source_ref" field.
func SourceRefHasSuffix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasSuffix(FieldSourceRef, v))
}

// SourceRefIsNil applies the IsNil predicate on the "source_ref" field.
func SourceRefIsNil() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIsNull(FieldSourceRef))
}

// SourceRefNotNil applies the NotNil predicate on the "source_ref" field.
func SourceRefNotNil() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotNull(FieldSourceRef))
}

// SourceRefEqualFold applies the EqualFold predicate on the "source_ref" field.
func SourceRefEqualFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEqualFold(FieldSourceRef, v))
}

// SourceRefContainsFold applies the ContainsFold predicate on the "source_ref" field.
func SourceRefContainsFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContainsFold(FieldSourceRef, v))
}

// ExtractionMethodEQ applies the EQ predicate on the "extraction_method" field.
func ExtractionMethodEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEQ(FieldExtractionMethod, v))
}

// ExtractionMethodNEQ applies the NEQ predicate on the "extraction_method" field.
func ExtractionMethodNEQ(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNEQ(FieldExtractionMethod, v))
}

// ExtractionMethodIn applies the In predicate on the "extraction_method" field.
func ExtractionMethodIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIn(FieldExtractionMethod, vs...))
}

// ExtractionMethodNotIn applies the NotIn predicate on the "extraction_method" field.
func ExtractionMethodNotIn(vs ...string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotIn(FieldExtractionMethod, vs...))
}

// ExtractionMethodGT applies the GT predicate on the "extraction_method" field.
func ExtractionMethodGT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGT(FieldExtractionMethod, v))
}

// ExtractionMethodGTE applies the GTE predicate on the "extraction_method" field.
func ExtractionMethodGTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldGTE(FieldExtractionMethod, v))
}

// ExtractionMethodLT applies the LT predicate on the "extraction_method" field.
func ExtractionMethodLT(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLT(FieldExtractionMethod, v))
}

// ExtractionMethodLTE applies the LTE predicate on the "extraction_method" field.
func ExtractionMethodLTE(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldLTE(FieldExtractionMethod, v))
}

// ExtractionMethodContains applies the Contains predicate on the "extraction_method" field.
func ExtractionMethodContains(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContains(FieldExtractionMethod, v))
}

// ExtractionMethodHasPrefix applies the HasPrefix predicate on the "extraction_method" field.
func ExtractionMethodHasPrefix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasPrefix(FieldExtractionMethod, v))
}

// ExtractionMethodHasSuffix applies the HasSuffix predicate on the "extraction_method" field.
func ExtractionMethodHasSuffix(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldHasSuffix(FieldExtractionMethod, v))
}

// ExtractionMethodEqualFold applies the EqualFold predicate on the "extraction_method" field.
func ExtractionMethodEqualFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldEqualFold(FieldExtractionMethod, v))
}

// ExtractionMethodContainsFold applies the ContainsFold predicate on the "extraction_method" field.
func ExtractionMethodContainsFold(v string) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldContainsFold(FieldExtractionMethod, v))
}

// AttributesIsNil applies the IsNil predicate on the "attributes" field.
func AttributesIsNil() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldIsNull(FieldAttributes))
}

// AttributesNotNil applies the NotNil predicate on the "attributes" field.
func AttributesNotNil() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.FieldNotNull(FieldAttributes))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Tenant
		step.Edge.Schema = schemaConfig.KnowledgeFactHistory
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(func(s *sql.Selector) {
		step := newTenantStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Tenant
		step.Edge.Schema = schemaConfig.KnowledgeFactHistory
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAlias applies the HasEdge predicate on the "alias" edge.
func HasAlias() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AliasTable, AliasColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeEntityAlias
		step.Edge.Schema = schemaConfig.KnowledgeFactHistory
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAliasWith applies the HasEdge predicate on the "alias" edge with a given conditions (other predicates).
func HasAliasWith(preds ...predicate.KnowledgeEntityAlias) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(func(s *sql.Selector) {
		step := newAliasStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeEntityAlias
		step.Edge.Schema = schemaConfig.KnowledgeFactHistory
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationship applies the HasEdge predicate on the "relationship" edge.
func HasRelationship() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RelationshipTable, RelationshipColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeRelationship
		step.Edge.Schema = schemaConfig.KnowledgeFactHistory
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipWith applies the HasEdge predicate on the "relationship" edge with a given conditions (other predicates).
func HasRelationshipWith(preds ...predicate.KnowledgeRelationship) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(func(s *sql.Selector) {
		step := newRelationshipStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeRelationship
		step.Edge.Schema = schemaConfig.KnowledgeFactHistory
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNormalizedEvent applies the HasEdge predicate on the "normalized_event" edge.
func HasNormalizedEvent() predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, NormalizedEventTable, NormalizedEventColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.NormalizedEvent
		step.Edge.Schema = schemaConfig.KnowledgeFactHistory
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNormalizedEventWith applies the HasEdge predicate on the "normalized_event" edge with a given conditions (other predicates).
func HasNormalizedEventWith(preds ...predicate.NormalizedEvent) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(func(s *sql.Selector) {
		step := newNormalizedEventStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.NormalizedEvent
		step.Edge.Schema = schemaConfig.KnowledgeFactHistory
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KnowledgeFactHistory) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KnowledgeFactHistory) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KnowledgeFactHistory) predicate.KnowledgeFactHistory {
	return predicate.KnowledgeFactHistory(sql.NotPredicates(p))
}
