// Code generated by ent, DO NOT EDIT.

package agentrunresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/rezible/rezible/ent/internal"
	"github.com/rezible/rezible/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldUpdatedAt, v))
}

// AgentRunID applies equality check predicate on the "agent_run_id" field. It's identical to AgentRunIDEQ.
func AgentRunID(v uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldAgentRunID, v))
}

// Output applies equality check predicate on the "output" field. It's identical to OutputEQ.
func Output(v []byte) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldOutput, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldErrorMessage, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNotIn(FieldTenantID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldLTE(FieldUpdatedAt, v))
}

// AgentRunIDEQ applies the EQ predicate on the "agent_run_id" field.
func AgentRunIDEQ(v uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldAgentRunID, v))
}

// AgentRunIDNEQ applies the NEQ predicate on the "agent_run_id" field.
func AgentRunIDNEQ(v uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNEQ(FieldAgentRunID, v))
}

// AgentRunIDIn applies the In predicate on the "agent_run_id" field.
func AgentRunIDIn(vs ...uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldIn(FieldAgentRunID, vs...))
}

// AgentRunIDNotIn applies the NotIn predicate on the "agent_run_id" field.
func AgentRunIDNotIn(vs ...uuid.UUID) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNotIn(FieldAgentRunID, vs...))
}

// OutputEQ applies the EQ predicate on the "output" field.
func OutputEQ(v []byte) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldOutput, v))
}

// OutputNEQ applies the NEQ predicate on the "output" field.
func OutputNEQ(v []byte) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNEQ(FieldOutput, v))
}

// OutputIn applies the In predicate on the "output" field.
func OutputIn(vs ...[]byte) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldIn(FieldOutput, vs...))
}

// OutputNotIn applies the NotIn predicate on the "output" field.
func OutputNotIn(vs ...[]byte) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNotIn(FieldOutput, vs...))
}

// OutputGT applies the GT predicate on the "output" field.
func OutputGT(v []byte) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldGT(FieldOutput, v))
}

// OutputGTE applies the GTE predicate on the "output" field.
func OutputGTE(v []byte) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldGTE(FieldOutput, v))
}

// OutputLT applies the LT predicate on the "output" field.
func OutputLT(v []byte) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldLT(FieldOutput, v))
}

// OutputLTE applies the LTE predicate on the "output" field.
func OutputLTE(v []byte) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldLTE(FieldOutput, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.FieldContainsFold(FieldErrorMessage, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.AgentRunResult {
	return predicate.AgentRunResult(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Tenant
		step.Edge.Schema = schemaConfig.AgentRunResult
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.AgentRunResult {
	return predicate.AgentRunResult(func(s *sql.Selector) {
		step := newTenantStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Tenant
		step.Edge.Schema = schemaConfig.AgentRunResult
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentRun applies the HasEdge predicate on the "agent_run" edge.
func HasAgentRun() predicate.AgentRunResult {
	return predicate.AgentRunResult(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AgentRunTable, AgentRunColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.AgentRun
		step.Edge.Schema = schemaConfig.AgentRunResult
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentRunWith applies the HasEdge predicate on the "agent_run" edge with a given conditions (other predicates).
func HasAgentRunWith(preds ...predicate.AgentRun) predicate.AgentRunResult {
	return predicate.AgentRunResult(func(s *sql.Selector) {
		step := newAgentRunStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.AgentRun
		step.Edge.Schema = schemaConfig.AgentRunResult
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentRunResult) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentRunResult) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentRunResult) predicate.AgentRunResult {
	return predicate.AgentRunResult(sql.NotPredicates(p))
}
