import {
    PUBLIC_APP_URL,
    PUBLIC_API_URL_BASE,
    PUBLIC_AUTH_ISSUER_URL,
    PUBLIC_AUTH_CLIENT_ID,
    PUBLIC_AUTH_CLIENT_SCOPES,
    PUBLIC_AUTH_CLIENT_REDIRECT_URI,
} from '$env/static/public';

export const APP_URL = PUBLIC_APP_URL;
export const API_URL_BASE = PUBLIC_API_URL_BASE || "/api/v1";
export const AUTH_ISSUER_URL = PUBLIC_AUTH_ISSUER_URL;
export const AUTH_CLIENT_ID = PUBLIC_AUTH_CLIENT_ID;
export const AUTH_CLIENT_SCOPES = PUBLIC_AUTH_CLIENT_SCOPES;
export const AUTH_CLIENT_REDIRECT_URI = PUBLIC_AUTH_CLIENT_REDIRECT_URI;