// Code generated by ent, DO NOT EDIT.

package aiagentrunknowledgecitation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/rezible/rezible/ent/internal"
	"github.com/rezible/rezible/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldUpdatedAt, v))
}

// AiAgentRunSnapshotID applies equality check predicate on the "ai_agent_run_snapshot_id" field. It's identical to AiAgentRunSnapshotIDEQ.
func AiAgentRunSnapshotID(v uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldAiAgentRunSnapshotID, v))
}

// KnowledgeEntityID applies equality check predicate on the "knowledge_entity_id" field. It's identical to KnowledgeEntityIDEQ.
func KnowledgeEntityID(v uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldKnowledgeEntityID, v))
}

// KnowledgeRelationshipID applies equality check predicate on the "knowledge_relationship_id" field. It's identical to KnowledgeRelationshipIDEQ.
func KnowledgeRelationshipID(v uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldKnowledgeRelationshipID, v))
}

// KnowledgeEvidenceID applies equality check predicate on the "knowledge_evidence_id" field. It's identical to KnowledgeEvidenceIDEQ.
func KnowledgeEvidenceID(v uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldKnowledgeEvidenceID, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldSummary, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNotIn(FieldTenantID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldLTE(FieldUpdatedAt, v))
}

// AiAgentRunSnapshotIDEQ applies the EQ predicate on the "ai_agent_run_snapshot_id" field.
func AiAgentRunSnapshotIDEQ(v uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldAiAgentRunSnapshotID, v))
}

// AiAgentRunSnapshotIDNEQ applies the NEQ predicate on the "ai_agent_run_snapshot_id" field.
func AiAgentRunSnapshotIDNEQ(v uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNEQ(FieldAiAgentRunSnapshotID, v))
}

// AiAgentRunSnapshotIDIn applies the In predicate on the "ai_agent_run_snapshot_id" field.
func AiAgentRunSnapshotIDIn(vs ...uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldIn(FieldAiAgentRunSnapshotID, vs...))
}

// AiAgentRunSnapshotIDNotIn applies the NotIn predicate on the "ai_agent_run_snapshot_id" field.
func AiAgentRunSnapshotIDNotIn(vs ...uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNotIn(FieldAiAgentRunSnapshotID, vs...))
}

// KnowledgeEntityIDEQ applies the EQ predicate on the "knowledge_entity_id" field.
func KnowledgeEntityIDEQ(v uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldKnowledgeEntityID, v))
}

// KnowledgeEntityIDNEQ applies the NEQ predicate on the "knowledge_entity_id" field.
func KnowledgeEntityIDNEQ(v uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNEQ(FieldKnowledgeEntityID, v))
}

// KnowledgeEntityIDIn applies the In predicate on the "knowledge_entity_id" field.
func KnowledgeEntityIDIn(vs ...uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldIn(FieldKnowledgeEntityID, vs...))
}

// KnowledgeEntityIDNotIn applies the NotIn predicate on the "knowledge_entity_id" field.
func KnowledgeEntityIDNotIn(vs ...uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNotIn(FieldKnowledgeEntityID, vs...))
}

// KnowledgeEntityIDIsNil applies the IsNil predicate on the "knowledge_entity_id" field.
func KnowledgeEntityIDIsNil() predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldIsNull(FieldKnowledgeEntityID))
}

// KnowledgeEntityIDNotNil applies the NotNil predicate on the "knowledge_entity_id" field.
func KnowledgeEntityIDNotNil() predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNotNull(FieldKnowledgeEntityID))
}

// KnowledgeRelationshipIDEQ applies the EQ predicate on the "knowledge_relationship_id" field.
func KnowledgeRelationshipIDEQ(v uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldKnowledgeRelationshipID, v))
}

// KnowledgeRelationshipIDNEQ applies the NEQ predicate on the "knowledge_relationship_id" field.
func KnowledgeRelationshipIDNEQ(v uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNEQ(FieldKnowledgeRelationshipID, v))
}

// KnowledgeRelationshipIDIn applies the In predicate on the "knowledge_relationship_id" field.
func KnowledgeRelationshipIDIn(vs ...uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldIn(FieldKnowledgeRelationshipID, vs...))
}

// KnowledgeRelationshipIDNotIn applies the NotIn predicate on the "knowledge_relationship_id" field.
func KnowledgeRelationshipIDNotIn(vs ...uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNotIn(FieldKnowledgeRelationshipID, vs...))
}

// KnowledgeRelationshipIDIsNil applies the IsNil predicate on the "knowledge_relationship_id" field.
func KnowledgeRelationshipIDIsNil() predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldIsNull(FieldKnowledgeRelationshipID))
}

// KnowledgeRelationshipIDNotNil applies the NotNil predicate on the "knowledge_relationship_id" field.
func KnowledgeRelationshipIDNotNil() predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNotNull(FieldKnowledgeRelationshipID))
}

// KnowledgeEvidenceIDEQ applies the EQ predicate on the "knowledge_evidence_id" field.
func KnowledgeEvidenceIDEQ(v uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldKnowledgeEvidenceID, v))
}

// KnowledgeEvidenceIDNEQ applies the NEQ predicate on the "knowledge_evidence_id" field.
func KnowledgeEvidenceIDNEQ(v uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNEQ(FieldKnowledgeEvidenceID, v))
}

// KnowledgeEvidenceIDIn applies the In predicate on the "knowledge_evidence_id" field.
func KnowledgeEvidenceIDIn(vs ...uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldIn(FieldKnowledgeEvidenceID, vs...))
}

// KnowledgeEvidenceIDNotIn applies the NotIn predicate on the "knowledge_evidence_id" field.
func KnowledgeEvidenceIDNotIn(vs ...uuid.UUID) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNotIn(FieldKnowledgeEvidenceID, vs...))
}

// KnowledgeEvidenceIDIsNil applies the IsNil predicate on the "knowledge_evidence_id" field.
func KnowledgeEvidenceIDIsNil() predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldIsNull(FieldKnowledgeEvidenceID))
}

// KnowledgeEvidenceIDNotNil applies the NotNil predicate on the "knowledge_evidence_id" field.
func KnowledgeEvidenceIDNotNil() predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNotNull(FieldKnowledgeEvidenceID))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.FieldContainsFold(FieldSummary, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Tenant
		step.Edge.Schema = schemaConfig.AiAgentRunKnowledgeCitation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(func(s *sql.Selector) {
		step := newTenantStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Tenant
		step.Edge.Schema = schemaConfig.AiAgentRunKnowledgeCitation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAiAgentRunSnapshot applies the HasEdge predicate on the "ai_agent_run_snapshot" edge.
func HasAiAgentRunSnapshot() predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AiAgentRunSnapshotTable, AiAgentRunSnapshotColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.AiAgentRunSnapshot
		step.Edge.Schema = schemaConfig.AiAgentRunKnowledgeCitation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAiAgentRunSnapshotWith applies the HasEdge predicate on the "ai_agent_run_snapshot" edge with a given conditions (other predicates).
func HasAiAgentRunSnapshotWith(preds ...predicate.AiAgentRunSnapshot) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(func(s *sql.Selector) {
		step := newAiAgentRunSnapshotStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.AiAgentRunSnapshot
		step.Edge.Schema = schemaConfig.AiAgentRunKnowledgeCitation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasKnowledgeEntity applies the HasEdge predicate on the "knowledge_entity" edge.
func HasKnowledgeEntity() predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, KnowledgeEntityTable, KnowledgeEntityColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeEntity
		step.Edge.Schema = schemaConfig.AiAgentRunKnowledgeCitation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKnowledgeEntityWith applies the HasEdge predicate on the "knowledge_entity" edge with a given conditions (other predicates).
func HasKnowledgeEntityWith(preds ...predicate.KnowledgeEntity) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(func(s *sql.Selector) {
		step := newKnowledgeEntityStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeEntity
		step.Edge.Schema = schemaConfig.AiAgentRunKnowledgeCitation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasKnowledgeRelationship applies the HasEdge predicate on the "knowledge_relationship" edge.
func HasKnowledgeRelationship() predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, KnowledgeRelationshipTable, KnowledgeRelationshipColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeRelationship
		step.Edge.Schema = schemaConfig.AiAgentRunKnowledgeCitation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKnowledgeRelationshipWith applies the HasEdge predicate on the "knowledge_relationship" edge with a given conditions (other predicates).
func HasKnowledgeRelationshipWith(preds ...predicate.KnowledgeRelationship) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(func(s *sql.Selector) {
		step := newKnowledgeRelationshipStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeRelationship
		step.Edge.Schema = schemaConfig.AiAgentRunKnowledgeCitation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasKnowledgeEvidence applies the HasEdge predicate on the "knowledge_evidence" edge.
func HasKnowledgeEvidence() predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, KnowledgeEvidenceTable, KnowledgeEvidenceColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeEvidence
		step.Edge.Schema = schemaConfig.AiAgentRunKnowledgeCitation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKnowledgeEvidenceWith applies the HasEdge predicate on the "knowledge_evidence" edge with a given conditions (other predicates).
func HasKnowledgeEvidenceWith(preds ...predicate.KnowledgeEvidence) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(func(s *sql.Selector) {
		step := newKnowledgeEvidenceStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.KnowledgeEvidence
		step.Edge.Schema = schemaConfig.AiAgentRunKnowledgeCitation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AiAgentRunKnowledgeCitation) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AiAgentRunKnowledgeCitation) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AiAgentRunKnowledgeCitation) predicate.AiAgentRunKnowledgeCitation {
	return predicate.AiAgentRunKnowledgeCitation(sql.NotPredicates(p))
}
