template: testify
filename: mocks.go
template-data:
  unroll-variadic: true
# all: true
packages:
  github.com/rezible/rezible:
    config:
      dir: .
      pkgname: mocks
    interfaces:
      JobsService: {}
      MessageService: {}
      OrganizationService: {}
      UserService: {}
