issuer: https://auth.dev.rezible.com

web:
  http: 0.0.0.0:7011
  allowedOrigins:
    - https://app.dev.rezible.com

storage:
  type: postgres
  config:
    host: postgres
    port: 5432
    database: dex_db
    user: dex
    password: foobar2
    ssl:
      mode: disable

oauth2:
  skipApprovalScreen: true
  responseTypes: ["code"]
  passwordConnector: local

enablePasswordDB: true
staticPasswords:
  - email: "admin@example.com"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
    # echo "foobar1" | htpasswd -BinC 10 admin | cut -d: -f2
    hash: "$2y$10$NI22AXHCKIordm2Y3pf0RuNVEUHvktOYruQ6/hli8UcvTEBhpX2KG"

staticClients:
  - id: rezible-app
    name: "Rezible"
    public: true
    redirectURIs:
      - https://app.dev.rezible.com/auth/callback
