#!/usr/bin/env just --justfile

@localias-reload:
    localias reload -c scripts/localias.yaml
    sleep 1
    mkdir -p scripts/certs && cat /etc/ssl/cert.pem "$(localias debug cert)" > ./scripts/certs/ca-bundle.crt

@run-docker-compose *CMD:
    docker compose \
      --env-file .env \
      -f ./scripts/docker-compose.yaml \
      {{CMD}}

@run-dev-services:
    just run-docker-compose up -d --wait

@stop-dev-services:
    just run-docker-compose down

@run-psql *ARGS:
    just run-docker-compose exec -it postgres psql -U rezible {{ARGS}}
