#!/usr/bin/env just --justfile

@localias-reload:
    localias reload -c scripts/localias.yaml
    mkdir -p scripts/certs && cat /etc/ssl/cert.pem "$(localias debug cert)" > ./scripts/certs/ca-bundle.crt

@run-docker-compose *CMD:
    docker compose \
      --env-file .env \
      -f ./scripts/docker-compose.yaml \
      {{CMD}}

@run-dev-services:
    just run-docker-compose up -d

@stop-dev-services:
    just run-docker-compose down

@provision-dev: run-dev-services
    just run-docker-compose up tf-provision

@get-provisioning-outputs:
    docker run --rm -v rezible-dev_terraform-data:/data alpine cat /data/output.json

@get-frontend-zitadel-client-id:
    echo -n "$(just get-provisioning-outputs)" | jq -r .application_client_id.value