// Code generated by ent, DO NOT EDIT.

package knowledgesubjectalias

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the knowledgesubjectalias type in the database.
	Label = "knowledge_subject_alias"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldSubjectKind holds the string denoting the subject_kind field in the database.
	FieldSubjectKind = "subject_kind"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldProviderSubjectRef holds the string denoting the provider_subject_ref field in the database.
	FieldProviderSubjectRef = "provider_subject_ref"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldRelationshipID holds the string denoting the relationship_id field in the database.
	FieldRelationshipID = "relationship_id"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldFirstObservedAt holds the string denoting the first_observed_at field in the database.
	FieldFirstObservedAt = "first_observed_at"
	// FieldLastObservedAt holds the string denoting the last_observed_at field in the database.
	FieldLastObservedAt = "last_observed_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeEvidence holds the string denoting the evidence edge name in mutations.
	EdgeEvidence = "evidence"
	// EdgeEntity holds the string denoting the entity edge name in mutations.
	EdgeEntity = "entity"
	// EdgeRelationship holds the string denoting the relationship edge name in mutations.
	EdgeRelationship = "relationship"
	// Table holds the table name of the knowledgesubjectalias in the database.
	Table = "knowledge_subject_alias"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "knowledge_subject_alias"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// EvidenceTable is the table that holds the evidence relation/edge.
	EvidenceTable = "knowledge_evidences"
	// EvidenceInverseTable is the table name for the KnowledgeEvidence entity.
	// It exists in this package in order to avoid circular dependency with the "knowledgeevidence" package.
	EvidenceInverseTable = "knowledge_evidences"
	// EvidenceColumn is the table column denoting the evidence relation/edge.
	EvidenceColumn = "alias_id"
	// EntityTable is the table that holds the entity relation/edge.
	EntityTable = "knowledge_subject_alias"
	// EntityInverseTable is the table name for the KnowledgeEntity entity.
	// It exists in this package in order to avoid circular dependency with the "knowledgeentity" package.
	EntityInverseTable = "knowledge_entities"
	// EntityColumn is the table column denoting the entity relation/edge.
	EntityColumn = "entity_id"
	// RelationshipTable is the table that holds the relationship relation/edge.
	RelationshipTable = "knowledge_subject_alias"
	// RelationshipInverseTable is the table name for the KnowledgeRelationship entity.
	// It exists in this package in order to avoid circular dependency with the "knowledgerelationship" package.
	RelationshipInverseTable = "knowledge_relationships"
	// RelationshipColumn is the table column denoting the relationship relation/edge.
	RelationshipColumn = "relationship_id"
)

// Columns holds all SQL columns for knowledgesubjectalias fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldSubjectKind,
	FieldProvider,
	FieldProviderSubjectRef,
	FieldEntityID,
	FieldRelationshipID,
	FieldDescription,
	FieldFirstObservedAt,
	FieldLastObservedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/rezible/rezible/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// ProviderSubjectRefValidator is a validator for the "provider_subject_ref" field. It is called by the builders before save.
	ProviderSubjectRefValidator func(string) error
	// DefaultFirstObservedAt holds the default value on creation for the "first_observed_at" field.
	DefaultFirstObservedAt func() time.Time
	// DefaultLastObservedAt holds the default value on creation for the "last_observed_at" field.
	DefaultLastObservedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// SubjectKind defines the type for the "subject_kind" enum field.
type SubjectKind string

// SubjectKind values.
const (
	SubjectKindEntity       SubjectKind = "entity"
	SubjectKindRelationship SubjectKind = "relationship"
)

func (sk SubjectKind) String() string {
	return string(sk)
}

// SubjectKindValidator is a validator for the "subject_kind" field enum values. It is called by the builders before save.
func SubjectKindValidator(sk SubjectKind) error {
	switch sk {
	case SubjectKindEntity, SubjectKindRelationship:
		return nil
	default:
		return fmt.Errorf("knowledgesubjectalias: invalid enum value for subject_kind field: %q", sk)
	}
}

// OrderOption defines the ordering options for the KnowledgeSubjectAlias queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// BySubjectKind orders the results by the subject_kind field.
func BySubjectKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectKind, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByProviderSubjectRef orders the results by the provider_subject_ref field.
func ByProviderSubjectRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderSubjectRef, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByRelationshipID orders the results by the relationship_id field.
func ByRelationshipID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelationshipID, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByFirstObservedAt orders the results by the first_observed_at field.
func ByFirstObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstObservedAt, opts...).ToFunc()
}

// ByLastObservedAt orders the results by the last_observed_at field.
func ByLastObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastObservedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByEvidenceCount orders the results by evidence count.
func ByEvidenceCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEvidenceStep(), opts...)
	}
}

// ByEvidence orders the results by evidence terms.
func ByEvidence(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEvidenceStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEntityField orders the results by entity field.
func ByEntityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntityStep(), sql.OrderByField(field, opts...))
	}
}

// ByRelationshipField orders the results by relationship field.
func ByRelationshipField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRelationshipStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
	)
}
func newEvidenceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EvidenceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, EvidenceTable, EvidenceColumn),
	)
}
func newEntityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, EntityTable, EntityColumn),
	)
}
func newRelationshipStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RelationshipInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RelationshipTable, RelationshipColumn),
	)
}
