CREATE USER rezible WITH LOGIN SUPERUSER PASSWORD 'foobar1';
CREATE DATABASE rezible OWNER rezible;
REVOKE ALL ON DATABASE rezible FROM PUBLIC;

CREATE USER dex WITH PASSWORD 'foobar2';
CREATE DATABASE dex_db OWNER dex;
GRANT ALL PRIVILEGES ON DATABASE dex_db TO dex;
