CREATE USER rezible WITH LOGIN SUPERUSER PASSWORD 'foobar1';
CREATE DATABASE rezible OWNER rezible;
REVOKE ALL ON DATABASE rezible FROM PUBLIC;

CREATE USER dex WITH PASSWORD 'foobar2';
CREATE DATABASE dex OWNER dex;
GRANT ALL PRIVILEGES ON DATABASE dex TO dex;
