filename: mocks.go
template: testify
template-data:
  unroll-variadic: true
# all: true
packages:
  github.com/rezible/rezible:
    config:
      dir: .
      pkgname: mocks
    interfaces:
      MessageService: {}
      JobsService: {}
      ProviderEventIngestorService: {}
      OrganizationService: {}
      UserService: {}