import {
    PUBLIC_APP_URL,
    PUBLIC_AUTH_URL,
    PUBLIC_AUTH_CLIENT_ID,
    PUBLIC_API_BASE_PATH,
    PUBLIC_API_V1_PATH,
} from '$env/static/public';

export const APP_URL = PUBLIC_APP_URL;
export const AUTH_URL = PUBLIC_AUTH_URL;
export const AUTH_CLIENT_ID = PUBLIC_AUTH_CLIENT_ID;
export const API_BASE_PATH = PUBLIC_API_BASE_PATH;
export const API_V1_PATH = API_BASE_PATH + PUBLIC_API_V1_PATH;