import {
    PUBLIC_APP_URL,
    PUBLIC_API_BASE_PATH,
    PUBLIC_API_V1_PATH,
    PUBLIC_API_AUTH_PATH,
} from '$env/static/public';

export const APP_URL = PUBLIC_APP_URL;
export const API_BASE_PATH = PUBLIC_API_BASE_PATH;
export const API_V1_PATH = API_BASE_PATH + PUBLIC_API_V1_PATH;
export const API_AUTH_PATH = API_BASE_PATH + PUBLIC_API_AUTH_PATH;