import {
    PUBLIC_APP_URL,
    PUBLIC_API_SERVER_URL,
    PUBLIC_API_BASE_PATH,
    PUBLIC_AUTH_SERVER_URL,
    PUBLIC_AUTH_APPLICATION_CLIENT_ID,
} from '$env/static/public';

export const APP_URL = PUBLIC_APP_URL;
export const API_URL = PUBLIC_API_SERVER_URL;
export const API_BASE_PATH = PUBLIC_API_BASE_PATH;
export const AUTH_URL = PUBLIC_AUTH_SERVER_URL;
export const AUTH_APP_CLIENT_ID = PUBLIC_AUTH_APPLICATION_CLIENT_ID;