CREATE USER rez_app WITH LOGIN PASSWORD 'rez_app';

REVOKE ALL ON DATABASE rezible FROM PUBLIC;

GRANT CONNECT ON DATABASE rezible TO rez_app;

CREATE SCHEMA IF NOT EXISTS river;
CREATE SCHEMA IF NOT EXISTS rezible;

GRANT USAGE ON SCHEMA rezible TO rez_app;
GRANT USAGE ON SCHEMA river TO rez_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA rezible
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rez_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA rezible
    GRANT USAGE, SELECT ON SEQUENCES TO rez_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA river
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rez_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA river
    GRANT USAGE, SELECT ON SEQUENCES TO rez_app;

ALTER ROLE rez_app SET search_path TO rezible, river;